import {
  fieldKeyMatchesNativePdfName,
  filterSuggestibleAcroformCatalogFields,
  isAcroformAutoGeneratedCatalogField,
  isSuggestibleAcroformCatalogField,
  normalizeNativePdfFieldKey,
} from "@/lib/acroform-catalog-field-filter";
import {
  shouldShowAcroformSuggestion,
  type AcroformPreselectContext,
} from "@/lib/acroform-match-preselect";
import { normalizeAcroformPdfFieldName } from "@/lib/acroform-field-mapping-memory";
import type { AcroformFieldMappingMemory } from "@/lib/types/acroform-field-mapping-memory";
import {
  fieldKeysAreSimilar,
  fieldLabelsAreSimilar,
  type Field,
} from "@/lib/types/field";

export type AcroformMatchKind =
  | "memory_form"
  | "memory_global"
  | "memory_normalized"
  | "exact_field_key"
  | "near_exact_field_key"
  | "label_similarity"
  | "heuristic";

export type AcroformFieldSuggestion = {
  field: Field;
  score: number;
  reason: string;
  matchKind: AcroformMatchKind;
  /** @deprecated Use matchKind */
  source?: "memory_form" | "memory_global" | "memory_normalized" | "heuristic";
};

export const ACROFORM_HIGH_CONFIDENCE_SCORE = 0.85;
export const ACROFORM_MIN_SUGGESTION_SCORE = 0.75;
export const ACROFORM_AUTO_PRESELECT_MIN_SCORE = 0.95;

export function normalizeAcroformMatchText(value: string): string {
  return normalizeAcroformPdfFieldName(value);
}

function normalizeMatchText(value: string): string {
  return normalizeAcroformMatchText(value);
}

function tokenize(value: string): string[] {
  return normalizeMatchText(value)
    .split("_")
    .filter((token) => token.length >= 3);
}

function tokenOverlapScore(left: string, right: string): number {
  const leftTokens = new Set(tokenize(left));
  const rightTokens = tokenize(right);
  if (leftTokens.size === 0 || rightTokens.length === 0) {
    return 0;
  }

  let overlap = 0;
  for (const token of rightTokens) {
    if (leftTokens.has(token)) {
      overlap += 1;
    }
  }

  return overlap / leftTokens.size;
}

function haystackIncludesAny(haystack: string, terms: string[]): boolean {
  const normalized = haystack.toLowerCase();
  return terms.some((term) => normalized.includes(term));
}

function hasDurableCatalogBinding(field: Field): boolean {
  if (field.resolver_key?.trim()) {
    return true;
  }

  if (field.source_path?.trim()) {
    return true;
  }

  const sourceType = field.source_type?.trim();
  return Boolean(sourceType && sourceType !== "manual_only");
}

function scoreAcroformCatalogMatch(
  pdfFieldName: string,
  pdfLabel: string,
  field: Field,
): AcroformFieldSuggestion | null {
  if (
    !isSuggestibleAcroformCatalogField(field, {
      pdfFieldName,
    })
  ) {
    return null;
  }

  const normalizedPdfKey = normalizeNativePdfFieldKey(pdfFieldName);
  const pdfHaystack = `${pdfFieldName} ${pdfLabel}`.trim();
  const fieldKey = field.field_key.trim();
  const fieldLabel = field.field_label?.trim() || field.field_name?.trim() || "";
  const fieldHaystack = [
    fieldKey,
    fieldLabel,
    field.source_path ?? "",
    field.resolver_key ?? "",
    field.notes ?? "",
  ]
    .filter(Boolean)
    .join(" ");

  let score = 0;
  const reasons: string[] = [];
  let matchKind: AcroformMatchKind = "heuristic";

  if (
    normalizedPdfKey &&
    normalizedPdfKey === fieldKey.toUpperCase() &&
    hasDurableCatalogBinding(field)
  ) {
    return {
      field,
      score: 1,
      reason: "Exact durable catalog field key match",
      matchKind: "exact_field_key",
    };
  }

  if (
    normalizedPdfKey &&
    fieldKeyMatchesNativePdfName(fieldKey, pdfFieldName)
  ) {
    return null;
  }

  if (
    normalizedPdfKey &&
    fieldKeysAreSimilar(
      normalizeMatchText(normalizedPdfKey),
      normalizeMatchText(fieldKey),
    )
  ) {
    score += 0.96;
    reasons.push("Near-exact field key");
    matchKind = "near_exact_field_key";
  }

  if (pdfLabel && fieldLabel && fieldLabelsAreSimilar(pdfLabel, fieldLabel)) {
    score += 0.68;
    reasons.push("Similar label");
    if (matchKind === "heuristic") {
      matchKind = "label_similarity";
    }
  }

  const overlap = tokenOverlapScore(pdfHaystack, fieldHaystack);
  if (overlap > 0) {
    score += overlap * 0.35;
    reasons.push("Shared terms");
  }

  if (
    haystackIncludesAny(pdfHaystack, [
      "address",
      "street",
      "city",
      "property",
      "location",
    ])
  ) {
    if (
      haystackIncludesAny(fieldKey, ["property", "address", "city", "street"]) ||
      haystackIncludesAny(field.resolver_key ?? "", [
        "property_address",
        "property_full",
      ])
    ) {
      score += 0.38;
      reasons.push("Property address match");
    }
  }

  if (haystackIncludesAny(pdfHaystack, ["seller", "landlord"])) {
    if (haystackIncludesAny(fieldKey, ["seller", "landlord"])) {
      score += 0.42;
      reasons.push("Seller-related field");
    }
  }

  if (haystackIncludesAny(pdfHaystack, ["buyer", "tenant"])) {
    if (haystackIncludesAny(fieldKey, ["buyer", "tenant"])) {
      score += 0.42;
      reasons.push("Buyer-related field");
    }
  }

  if (
    field.resolver_key &&
    haystackIncludesAny(pdfHaystack, ["address", "city"]) &&
    field.resolver_key.toLowerCase().includes("property_address")
  ) {
    score += 0.25;
    reasons.push("Property resolver match");
  }

  if (hasDurableCatalogBinding(field)) {
    score += 0.08;
    reasons.push("Durable catalog binding");
  }

  const finalScore = Math.min(1, score);
  if (finalScore < ACROFORM_MIN_SUGGESTION_SCORE) {
    return null;
  }

  return {
    field,
    score: finalScore,
    reason: reasons.length > 0 ? reasons.join(" · ") : "Possible match",
    matchKind,
  };
}

export function isHighConfidenceAcroformSuggestion(
  suggestion: Pick<AcroformFieldSuggestion, "score" | "matchKind">,
): boolean {
  return suggestion.score >= ACROFORM_AUTO_PRESELECT_MIN_SCORE;
}

export function isSuggestedAcroformMatch(
  suggestion: Pick<AcroformFieldSuggestion, "score">,
): boolean {
  return suggestion.score >= ACROFORM_MIN_SUGGESTION_SCORE;
}

export function suggestAcroformFieldMatches(
  pdfFieldName: string,
  pdfLabel: string,
  catalogFields: Field[],
  options?: {
    excludeFieldId?: string | null;
    limit?: number;
  },
): AcroformFieldSuggestion[] {
  const limit = options?.limit ?? 5;
  const excludeFieldId = options?.excludeFieldId ?? null;

  const scored = filterSuggestibleAcroformCatalogFields(catalogFields, {
    pdfFieldName,
  })
    .filter((field) => field.id !== excludeFieldId)
    .map((field) => scoreAcroformCatalogMatch(pdfFieldName, pdfLabel, field))
    .filter((suggestion): suggestion is AcroformFieldSuggestion => suggestion != null)
    .sort((left, right) => {
      if (right.score !== left.score) {
        return right.score - left.score;
      }

      return left.field.field_key.localeCompare(right.field.field_key);
    });

  return scored.slice(0, limit);
}

export function findHighConfidenceAcroformMatch(
  pdfFieldName: string,
  pdfLabel: string,
  catalogFields: Field[],
): AcroformFieldSuggestion | null {
  const [best] = suggestAcroformFieldMatches(pdfFieldName, pdfLabel, catalogFields, {
    limit: 1,
  });

  if (!best || !isHighConfidenceAcroformSuggestion(best)) {
    return null;
  }

  return best;
}

function mergeSuggestions(
  suggestions: AcroformFieldSuggestion[],
  limit: number,
): AcroformFieldSuggestion[] {
  const byFieldId = new Map<string, AcroformFieldSuggestion>();

  for (const suggestion of suggestions) {
    if (isAcroformAutoGeneratedCatalogField(suggestion.field)) {
      continue;
    }

    const existing = byFieldId.get(suggestion.field.id);
    if (!existing || suggestion.score > existing.score) {
      byFieldId.set(suggestion.field.id, suggestion);
    }
  }

  return [...byFieldId.values()]
    .filter((suggestion) => suggestion.score >= ACROFORM_MIN_SUGGESTION_SCORE)
    .sort((left, right) => {
      if (right.score !== left.score) {
        return right.score - left.score;
      }

      return left.field.field_key.localeCompare(right.field.field_key);
    })
    .slice(0, limit);
}

function attachLegacySource(
  suggestion: AcroformFieldSuggestion,
): AcroformFieldSuggestion {
  const legacySource =
    suggestion.matchKind === "memory_form"
      ? "memory_form"
      : suggestion.matchKind === "memory_global"
        ? "memory_global"
        : suggestion.matchKind === "memory_normalized"
          ? "memory_normalized"
          : "heuristic";

  return {
    ...suggestion,
    source: legacySource,
  };
}

export function suggestAcroformFieldMatchesWithMemory(
  pdfFieldName: string,
  pdfLabel: string,
  catalogFields: Field[],
  memoryEntries: AcroformFieldMappingMemory[],
  options?: {
    formCode?: string | null;
    formName?: string | null;
    excludeFieldId?: string | null;
    limit?: number;
  },
): AcroformFieldSuggestion[] {
  const limit = options?.limit ?? 5;
  const formCode = options?.formCode?.trim() || null;
  const formName = options?.formName?.trim() || null;
  const normalizedPdf = normalizeAcroformPdfFieldName(pdfFieldName);
  const catalogById = new Map(catalogFields.map((field) => [field.id, field]));
  const memorySuggestions: AcroformFieldSuggestion[] = [];
  const displayContext: Pick<
    AcroformPreselectContext,
    "formCode" | "formName" | "pdfFieldName" | "pdfLabel"
  > = {
    formCode,
    formName,
    pdfFieldName,
    pdfLabel,
  };

  for (const entry of memoryEntries) {
    const field = entry.fields ?? catalogById.get(entry.field_id);
    if (
      !field ||
      !isSuggestibleAcroformCatalogField(field, {
        pdfFieldName,
      })
    ) {
      continue;
    }

    const entryName = entry.pdf_field_name.trim().toLowerCase();
    const targetName = pdfFieldName.trim().toLowerCase();

    if (formCode && entry.form_code === formCode && entryName === targetName) {
      memorySuggestions.push(
        attachLegacySource({
          field,
          score: 1,
          reason: "Remembered mapping for this form",
          matchKind: "memory_form",
        }),
      );
      continue;
    }

    if (entryName === targetName) {
      memorySuggestions.push(
        attachLegacySource({
          field,
          score: 0.98,
          reason: "Remembered mapping (global)",
          matchKind: "memory_global",
        }),
      );
      continue;
    }

    const entryNormalized =
      entry.normalized_pdf_field_name ??
      normalizeAcroformPdfFieldName(entry.pdf_field_name);
    if (
      entryNormalized &&
      normalizedPdf &&
      (entryNormalized === normalizedPdf ||
        fieldKeysAreSimilar(entryNormalized, normalizedPdf))
    ) {
      memorySuggestions.push(
        attachLegacySource({
          field,
          score: 0.92,
          reason: "Remembered normalized PDF field match",
          matchKind: "memory_normalized",
        }),
      );
    }
  }

  const heuristicSuggestions = suggestAcroformFieldMatches(
    pdfFieldName,
    pdfLabel,
    catalogFields,
    {
      excludeFieldId: options?.excludeFieldId,
      limit: limit * 2,
    },
  ).map((suggestion) => attachLegacySource(suggestion));

  return mergeSuggestions(
    [...memorySuggestions, ...heuristicSuggestions],
    limit,
  ).filter((suggestion) => shouldShowAcroformSuggestion(suggestion, displayContext));
}
