import { normalizeAcroformPdfFieldName } from "@/lib/acroform-field-mapping-memory";
import type { Field } from "@/lib/types/field";

/** Same normalization used when deriving keys from native PDF field names. */
export function normalizeNativePdfFieldKey(rawName: string): string {
  return rawName
    .trim()
    .replace(/[^\w.-]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .replace(/_{2,}/g, "_")
    .toUpperCase();
}

const EXPLICIT_USER_CREATED_ACROFORM_NOTE =
  /created during acroform import review/i;

const AUTO_ACROFORM_CATALOG_NOTE_PATTERNS = [
  /imported from pdf acroform field inventory/i,
  /imported from pdf field inventory/i,
  /imported from pdf acroform/i,
  /auto.?created.*acroform/i,
];

export function isExplicitAcroformUserCreatedField(field: Field): boolean {
  return EXPLICIT_USER_CREATED_ACROFORM_NOTE.test(field.notes?.trim() ?? "");
}

export function isRawNativePdfStyleFieldKey(fieldKey: string): boolean {
  const key = fieldKey.trim();
  if (!key || !/^[A-Z0-9_]+$/.test(key)) {
    return false;
  }

  const segments = key.split("_").filter(Boolean);
  return segments.length >= 3 || key.length >= 18;
}

export function fieldKeyMatchesNativePdfName(
  fieldKey: string,
  pdfFieldName: string,
): boolean {
  const normalizedPdfKey = normalizeNativePdfFieldKey(pdfFieldName);
  if (!normalizedPdfKey) {
    return false;
  }

  return fieldKey.trim().toUpperCase() === normalizedPdfKey;
}

function hasDurableCatalogBinding(field: Field): boolean {
  if (field.resolver_key?.trim()) {
    return true;
  }

  if (field.source_path?.trim()) {
    return true;
  }

  const sourceType = field.source_type?.trim();
  return Boolean(sourceType && sourceType !== "manual_only");
}

/**
 * Catalog fields that look like auto-created placeholders from native PDF names.
 * Explicit user-created fields during import review are never treated as pollution.
 */
export function isAcroformAutoGeneratedCatalogField(field: Field): boolean {
  if (isExplicitAcroformUserCreatedField(field)) {
    return false;
  }

  const notes = field.notes?.trim() ?? "";
  if (
    AUTO_ACROFORM_CATALOG_NOTE_PATTERNS.some((pattern) => pattern.test(notes))
  ) {
    return true;
  }

  const fieldKey = field.field_key.trim();
  if (!isRawNativePdfStyleFieldKey(fieldKey)) {
    return false;
  }

  if (hasDurableCatalogBinding(field)) {
    return false;
  }

  return true;
}

export function isSuggestibleAcroformCatalogField(
  field: Field,
  options?: {
    pdfFieldName?: string | null;
  },
): boolean {
  if (field.status !== "ACTIVE") {
    return false;
  }

  if (isAcroformAutoGeneratedCatalogField(field)) {
    return false;
  }

  const pdfFieldName = options?.pdfFieldName?.trim();
  if (
    pdfFieldName &&
    fieldKeyMatchesNativePdfName(field.field_key, pdfFieldName) &&
    !hasDurableCatalogBinding(field)
  ) {
    return false;
  }

  return true;
}

export function filterSuggestibleAcroformCatalogFields(
  fields: Field[],
  options?: {
    pdfFieldName?: string | null;
  },
): Field[] {
  return fields.filter((field) => isSuggestibleAcroformCatalogField(field, options));
}

export function resolveSuggestibleAcroformFieldId(
  fieldId: string | null | undefined,
  catalogFields: Field[],
  options?: {
    pdfFieldName?: string | null;
  },
): string | null {
  if (!fieldId) {
    return null;
  }

  const field = catalogFields.find((entry) => entry.id === fieldId);
  if (!field) {
    return null;
  }

  return isSuggestibleAcroformCatalogField(field, options) ? field.id : null;
}

/** Lowercase catalog-style key hint for explicit create flows (never auto-persisted). */
export function suggestCatalogKeyFromPdfFieldName(pdfFieldName: string): string {
  return normalizeAcroformPdfFieldName(pdfFieldName);
}

export function humanizePdfFieldName(pdfFieldName: string): string {
  return suggestCatalogKeyFromPdfFieldName(pdfFieldName)
    .split("_")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
