export type UserAgentSettingsStatus = "ACTIVE" | "INACTIVE" | "DELETED";

export type UserAgentSettings = {
  user_id: string;
  create_date: string;
  update_date: string;
  status: UserAgentSettingsStatus;
  legal_first_name: string | null;
  legal_middle_name: string | null;
  legal_last_name: string | null;
  preferred_name: string | null;
  display_name: string | null;
  email: string | null;
  phone: string | null;
  phone_alternate: string | null;
  address_line_1: string | null;
  address_line_2: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
  trec_license_number: string | null;
  title: string | null;
  trec_license_type?: string | null;
  trec_reported_full_name?: string | null;
  trec_license_status?: string | null;
  trec_expiration_date?: string | null;
  trec_related_license_number?: string | null;
  trec_related_license_name?: string | null;
  trec_lookup_at?: string | null;
  license_verified_at?: string | null;
  license_verification_source?: "trec" | "manual" | null;
  license_manual_override_reason?: string | null;
  license_verified_by_user_id?: string | null;
};
