/**
 * Regenerates `lib/signing/mark-metrics-data.ts` from the fonts the
 * completed-PDF renderer embeds (Caveat for typed marks, Helvetica for Date
 * Signed), so Draft placement defaults can measure marks in the browser.
 *
 *   npx tsx --tsconfig tsconfig.json scripts/generate-signing-mark-metrics.ts
 */
import fontkit from "@pdf-lib/fontkit";
import { readFileSync, writeFileSync } from "node:fs";
import { PDFDocument, StandardFonts } from "pdf-lib";

async function main() {
  const doc = await PDFDocument.create();
  doc.registerFontkit(fontkit as Parameters<PDFDocument["registerFontkit"]>[0]);
  const caveat = await doc.embedFont(readFileSync("public/fonts/Caveat-Regular.ttf"));
  const helvetica = await doc.embedFont(StandardFonts.Helvetica);

  const caveatWidths: Record<string, number> = {};
  for (let code = 32; code <= 126; code += 1) {
    const char = String.fromCharCode(code);
    caveatWidths[char] = Math.round(caveat.widthOfTextAtSize(char, 1000));
  }
  const caveatDescent = Math.round(
    Math.abs(
      caveat.heightAtSize(1000, { descender: true }) -
        caveat.heightAtSize(1000, { descender: false }),
    ),
  );
  const helveticaWidths: Record<string, number> = {};
  for (const char of "0123456789-") {
    helveticaWidths[char] = Math.round(helvetica.widthOfTextAtSize(char, 1000));
  }

  const body = `/**
 * Generated by scripts/generate-signing-mark-metrics.ts — do not edit.
 * Advance widths in 1/1000 em for the fonts the completed-PDF renderer embeds.
 */

export const CAVEAT_ADVANCE_WIDTHS: Readonly<Record<string, number>> = ${JSON.stringify(caveatWidths, null, 2)};

/** Descender depth in 1/1000 em (pdf-lib heightAtSize with vs without descender). */
export const CAVEAT_DESCENT = ${caveatDescent};

export const HELVETICA_DATE_ADVANCE_WIDTHS: Readonly<Record<string, number>> = ${JSON.stringify(helveticaWidths, null, 2)};
`;
  writeFileSync("lib/signing/mark-metrics-data.ts", body);
  console.log("wrote lib/signing/mark-metrics-data.ts");
}

main();
