-- Common Texas real estate property fields (additive columns only).

alter table public.properties
  add column if not exists lot text,
  add column if not exists block text,
  add column if not exists addition text,
  add column if not exists subdivision text,
  add column if not exists tax_id text,
  add column if not exists geo_id text,
  add column if not exists school_district text,
  add column if not exists municipality text,
  add column if not exists etj text,
  add column if not exists stories numeric,
  add column if not exists garage_spaces numeric,
  add column if not exists garage_type text,
  add column if not exists pool boolean not null default false,
  add column if not exists spa boolean not null default false,
  add column if not exists fireplace boolean not null default false,
  add column if not exists basement boolean not null default false,
  add column if not exists sprinkler_system boolean not null default false,
  add column if not exists waterfront boolean not null default false,
  add column if not exists water_view boolean not null default false,
  add column if not exists corner_lot boolean not null default false,
  add column if not exists cul_de_sac boolean not null default false,
  add column if not exists gated boolean not null default false,
  add column if not exists new_construction boolean not null default false,
  add column if not exists well boolean not null default false,
  add column if not exists septic boolean not null default false,
  add column if not exists solar boolean not null default false,
  add column if not exists propane boolean not null default false,
  add column if not exists electric_provider text,
  add column if not exists gas_provider text,
  add column if not exists water_provider text,
  add column if not exists sewer_provider text,
  add column if not exists has_hoa boolean not null default false,
  add column if not exists hoa_name text,
  add column if not exists hoa_management_company text,
  add column if not exists hoa_contact_name text,
  add column if not exists hoa_phone text,
  add column if not exists hoa_email text,
  add column if not exists hoa_website text,
  add column if not exists hoa_dues_amount numeric,
  add column if not exists hoa_dues_frequency text,
  add column if not exists occupancy_status text;
