-- TXR-1101 Residential Real Estate Listing Agreement reusable field catalog seeds.
-- Form metadata and PDF placements are managed separately (do not touch public.forms).

-- ---------------------------------------------------------------------------
-- Expand fields.source_type for listing agreement-backed resolver paths
-- ---------------------------------------------------------------------------

alter table public.fields
  drop constraint if exists fields_source_type_check;

alter table public.fields
  add constraint fields_source_type_check
  check (
    source_type is null
    or source_type in (
      'settings_agent',
      'settings_brokerage',
      'packet_contact',
      'packet_property',
      'packet',
      'buyer_rep_details',
      'listing_agreement_details',
      'representation_agreement',
      'static_default',
      'custom_resolver',
      'manual_only'
    )
  );

-- ---------------------------------------------------------------------------
-- fields — idempotent upsert by field_key (active rows)
-- ---------------------------------------------------------------------------

with seed (
  field_key,
  field_name,
  field_label,
  field_data_type,
  field_widget_type,
  default_value,
  default_checked,
  required,
  notes,
  source_type,
  source_path,
  resolver_key
) as (
  values
    -- Seller / contact fields
    (
      'seller_name_1',
      'seller_name_1',
      'Seller Name 1',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · First active seller contact name by sort_order.',
      'packet_contact',
      'seller_1.full_name',
      null::text
    ),
    (
      'seller_name_2',
      'seller_name_2',
      'Seller Name 2',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Second active seller contact name by sort_order.',
      'packet_contact',
      'seller_2.full_name',
      null::text
    ),
    (
      'seller_address',
      'seller_address',
      'Seller Address',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Primary seller mailing address lines.',
      'custom_resolver',
      null::text,
      'seller_address'
    ),
    (
      'seller_city_state_zip',
      'seller_city_state_zip',
      'Seller City, State ZIP',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Primary seller city, state, and ZIP.',
      'custom_resolver',
      null::text,
      'seller_city_state_zip'
    ),
    (
      'seller_phone',
      'seller_phone',
      'Seller Phone',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Primary seller phone from packet contacts.',
      'packet_contact',
      'seller_1.phone',
      null::text
    ),
    (
      'seller_email',
      'seller_email',
      'Seller Email',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Primary seller email from packet contacts.',
      'packet_contact',
      'seller_1.email',
      null::text
    ),

    -- Page header
    (
      'listing_agreement_concerning',
      'listing_agreement_concerning',
      'Listing Agreement Concerning',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Property street address and city from packet property.',
      'custom_resolver',
      null::text,
      'listing_agreement_concerning'
    ),

    -- Property fields
    (
      'property_lot',
      'property_lot',
      'Property Lot',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Property lot from packet property.',
      'packet_property',
      'lot',
      null::text
    ),
    (
      'property_block',
      'property_block',
      'Property Block',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Property block from packet property.',
      'packet_property',
      'block',
      null::text
    ),
    (
      'property_addition',
      'property_addition',
      'Property Addition',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Property addition/subdivision from packet property.',
      'packet_property',
      'subdivision',
      null::text
    ),
    (
      'property_city',
      'property_city',
      'Property City',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Property city from packet property.',
      'packet_property',
      'city',
      null::text
    ),
    (
      'property_county',
      'property_county',
      'Property County',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Property county from packet property.',
      'packet_property',
      'county',
      null::text
    ),
    (
      'property_address_zip',
      'property_address_zip',
      'Property ZIP',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Property ZIP from packet property.',
      'packet_property',
      'zip',
      null::text
    ),
    (
      'property_legal_description',
      'property_legal_description',
      'Property Legal Description',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Property legal description from packet property.',
      'packet_property',
      'legal_description',
      null::text
    ),
    (
      'listing_exclusions',
      'listing_exclusions',
      'Listing Exclusions',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Exclusions from listing_agreement_details.',
      'listing_agreement_details',
      'exclusions',
      null::text
    ),
    (
      'listing_hoa_is_subject',
      'listing_hoa_is_subject',
      'Property Is Subject to HOA',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · HOA subject (Paragraph 2E) from listing_agreement_details.',
      'listing_agreement_details',
      'hoa_exists',
      null::text
    ),
    (
      'listing_hoa_is_not_subject',
      'listing_hoa_is_not_subject',
      'Property Is Not Subject to HOA',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Inverse of HOA subject (Paragraph 2E).',
      'custom_resolver',
      null::text,
      'listing_hoa_is_not_subject'
    ),

    -- Listing agreement detail fields
    (
      'listing_price',
      'listing_price',
      'Listing Price',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · List price from listing_agreement_details.',
      'listing_agreement_details',
      'list_price',
      null::text
    ),
    (
      'listing_begin_date',
      'listing_begin_date',
      'Listing Begin Date',
      'date',
      'date',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Listing term begin date from listing_agreement_details.',
      'listing_agreement_details',
      'listing_begin_date',
      null::text
    ),
    (
      'listing_end_date',
      'listing_end_date',
      'Listing End Date',
      'date',
      'date',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Listing term end date from listing_agreement_details.',
      'listing_agreement_details',
      'listing_end_date',
      null::text
    ),
    (
      'listing_compensation_model_with_coop',
      'listing_compensation_model_with_coop',
      'Compensation Model With Co-op',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Broker with cooperating brokers compensation model.',
      'custom_resolver',
      null::text,
      'listing_compensation_model_with_coop'
    ),
    (
      'listing_compensation_model_no_coop',
      'listing_compensation_model_no_coop',
      'Compensation Model No Co-op',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Broker without cooperating brokers compensation model.',
      'custom_resolver',
      null::text,
      'listing_compensation_model_no_coop'
    ),
    (
      'listing_commission_percent',
      'listing_commission_percent',
      'Listing Commission Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Listing commission percent from listing_agreement_details.',
      'listing_agreement_details',
      'listing_commission_percent',
      null::text
    ),
    (
      'listing_flat_fee',
      'listing_flat_fee',
      'Listing Flat Fee',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Listing flat fee from listing_agreement_details.',
      'listing_agreement_details',
      'listing_flat_fee',
      null::text
    ),
    (
      'listing_compensation_other',
      'listing_compensation_other',
      'Listing Compensation Other',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Other listing compensation from listing_agreement_details.',
      'listing_agreement_details',
      'listing_compensation_other',
      null::text
    ),
    (
      'buyer_broker_comp_percent',
      'buyer_broker_comp_percent',
      'Buyer Broker Compensation Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Buyer broker compensation percent from listing_agreement_details.',
      'listing_agreement_details',
      'buyer_broker_comp_percent',
      null::text
    ),
    (
      'buyer_broker_comp_flat_fee',
      'buyer_broker_comp_flat_fee',
      'Buyer Broker Compensation Flat Fee',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Buyer broker compensation flat fee from listing_agreement_details.',
      'listing_agreement_details',
      'buyer_broker_comp_flat_fee',
      null::text
    ),
    (
      'seller_authorizes_buyer_expense_disclosure_yes',
      'seller_authorizes_buyer_expense_disclosure_yes',
      'Seller Authorizes Buyer Expense Disclosure Yes',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Seller authorizes buyer expense disclosure from listing_agreement_details.',
      'listing_agreement_details',
      'seller_authorizes_buyer_expense_disclosure',
      null::text
    ),
    (
      'seller_authorizes_buyer_expense_disclosure_no',
      'seller_authorizes_buyer_expense_disclosure_no',
      'Seller Authorizes Buyer Expense Disclosure No',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Inverse of seller authorizes buyer expense disclosure.',
      'custom_resolver',
      null::text,
      'seller_authorizes_buyer_expense_disclosure_no'
    ),
    (
      'other_fees_reimbursable_expenses',
      'other_fees_reimbursable_expenses',
      'Other Fees and Reimbursable Expenses',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Other fees and reimbursable expenses from listing_agreement_details.',
      'listing_agreement_details',
      'other_fees_reimbursable_expenses',
      null::text
    ),
    (
      'listing_protection_period_days',
      'listing_protection_period_days',
      'Listing Protection Period Days',
      'integer',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Protection period days from listing_agreement_details.',
      'listing_agreement_details',
      'protection_period_days',
      null::text
    ),
    (
      'listing_payment_county',
      'listing_payment_county',
      'Listing Payment County',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · County for payment from listing_agreement_details.',
      'listing_agreement_details',
      'payment_county',
      null::text
    ),
    (
      'mls_file_listing',
      'mls_file_listing',
      'MLS File Listing',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · MLS filing authorized (any option except no MLS).',
      'custom_resolver',
      null::text,
      'mls_file_listing'
    ),
    (
      'mls_file_immediately',
      'mls_file_immediately',
      'MLS File Immediately',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · File listing in MLS immediately.',
      'custom_resolver',
      null::text,
      'mls_file_immediately'
    ),
    (
      'mls_delay_filing',
      'mls_delay_filing',
      'MLS Delay Filing',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Delayed MLS filing option.',
      'custom_resolver',
      null::text,
      'mls_delay_filing'
    ),
    (
      'mls_delayed_days',
      'mls_delayed_days',
      'MLS Delayed Days',
      'integer',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · MLS delayed filing days from listing_agreement_details.',
      'listing_agreement_details',
      'mls_delayed_days',
      null::text
    ),
    (
      'mls_delayed_purpose',
      'mls_delayed_purpose',
      'MLS Delayed Purpose',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · MLS delayed filing purpose from listing_agreement_details.',
      'listing_agreement_details',
      'mls_delayed_purpose',
      null::text
    ),
    (
      'mls_no_filing',
      'mls_no_filing',
      'MLS No Filing',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Do not file listing in MLS.',
      'custom_resolver',
      null::text,
      'mls_no_filing'
    ),
    (
      'scheduling_company',
      'scheduling_company',
      'Scheduling Company',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Showing scheduling company from listing_agreement_details.',
      'listing_agreement_details',
      'scheduling_company',
      null::text
    ),
    (
      'keybox_authorized_yes',
      'keybox_authorized_yes',
      'Keybox Authorized Yes',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Keybox authorized from listing_agreement_details.',
      'listing_agreement_details',
      'keybox_authorized',
      null::text
    ),
    (
      'keybox_authorized_no',
      'keybox_authorized_no',
      'Keybox Authorized No',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Inverse of keybox authorized.',
      'custom_resolver',
      null::text,
      'keybox_authorized_no'
    ),
    (
      'listing_intermediary_yes',
      'listing_intermediary_yes',
      'Listing Intermediary Yes',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Intermediary allowed from listing_agreement_details.',
      'listing_agreement_details',
      'intermediary_allowed',
      null::text
    ),
    (
      'listing_intermediary_no',
      'listing_intermediary_no',
      'Listing Intermediary No',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Inverse of intermediary allowed.',
      'custom_resolver',
      null::text,
      'listing_intermediary_no'
    ),
    (
      'internet_no_display',
      'internet_no_display',
      'No Internet Display',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · No internet display option.',
      'custom_resolver',
      null::text,
      'internet_no_display'
    ),
    (
      'internet_no_address_display',
      'internet_no_address_display',
      'No Address Internet Display',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · No address on internet display option.',
      'custom_resolver',
      null::text,
      'internet_no_address_display'
    ),
    (
      'financing_conventional',
      'financing_conventional',
      'Financing Conventional',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Conventional financing from listing_agreement_details.',
      'listing_agreement_details',
      'financing_conventional',
      null::text
    ),
    (
      'financing_va',
      'financing_va',
      'Financing VA',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · VA financing from listing_agreement_details.',
      'listing_agreement_details',
      'financing_va',
      null::text
    ),
    (
      'financing_fha',
      'financing_fha',
      'Financing FHA',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · FHA financing from listing_agreement_details.',
      'listing_agreement_details',
      'financing_fha',
      null::text
    ),
    (
      'financing_cash',
      'financing_cash',
      'Financing Cash',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Cash financing from listing_agreement_details.',
      'listing_agreement_details',
      'financing_cash',
      null::text
    ),
    (
      'financing_texas_veterans',
      'financing_texas_veterans',
      'Financing Texas Veterans',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Texas veterans financing from listing_agreement_details.',
      'listing_agreement_details',
      'financing_texas_veterans',
      null::text
    ),
    (
      'financing_owner_finance',
      'financing_owner_finance',
      'Financing Owner Finance',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Owner finance from listing_agreement_details.',
      'listing_agreement_details',
      'financing_owner_finance',
      null::text
    ),
    (
      'financing_other',
      'financing_other',
      'Financing Other',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Other financing from listing_agreement_details.',
      'listing_agreement_details',
      'financing_other',
      null::text
    ),
    (
      'financing_other_description',
      'financing_other_description',
      'Financing Other Description',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Other financing description from listing_agreement_details.',
      'listing_agreement_details',
      'financing_other_description',
      null::text
    ),
    (
      'known_financial_obligations_exception',
      'known_financial_obligations_exception',
      'Known Financial Obligations Exception',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Known financial obligations exception from listing_agreement_details.',
      'listing_agreement_details',
      'known_financial_obligations_exception',
      null::text
    ),
    (
      'known_liens_exception',
      'known_liens_exception',
      'Known Liens Exception',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Known liens exception from listing_agreement_details.',
      'listing_agreement_details',
      'known_liens_exception',
      null::text
    ),
    (
      'employer_relocation_company',
      'employer_relocation_company',
      'Employer Relocation Company',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Employer relocation company from listing_agreement_details.',
      'listing_agreement_details',
      'employer_relocation_company',
      null::text
    ),
    (
      'known_districts',
      'known_districts',
      'Known Districts',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Known districts from listing_agreement_details.',
      'listing_agreement_details',
      'known_districts',
      null::text
    ),
    (
      'listing_special_provisions',
      'listing_special_provisions',
      'Listing Special Provisions',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Special provisions from listing_agreement_details.',
      'listing_agreement_details',
      'special_provisions',
      null::text
    ),

    -- Addenda fields
    (
      'listing_add_iabs',
      'listing_add_iabs',
      'Add IABS',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include IABS addendum from listing_agreement_details.',
      'listing_agreement_details',
      'add_iabs',
      null::text
    ),
    (
      'listing_add_sellers_disclosure',
      'listing_add_sellers_disclosure',
      'Add Seller''s Disclosure',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include seller''s disclosure from listing_agreement_details.',
      'listing_agreement_details',
      'add_sellers_disclosure',
      null::text
    ),
    (
      'listing_add_lead_paint',
      'listing_add_lead_paint',
      'Add Lead Paint',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include lead paint addendum from listing_agreement_details.',
      'listing_agreement_details',
      'add_lead_paint',
      null::text
    ),
    (
      'listing_add_t47',
      'listing_add_t47',
      'Add T-47',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include T-47 addendum from listing_agreement_details.',
      'listing_agreement_details',
      'add_t47',
      null::text
    ),
    (
      'listing_add_mud_notice',
      'listing_add_mud_notice',
      'Add MUD Notice',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include MUD notice from listing_agreement_details.',
      'listing_agreement_details',
      'add_mud_notice',
      null::text
    ),
    (
      'listing_add_pid_notice',
      'listing_add_pid_notice',
      'Add PID Notice',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include PID notice from listing_agreement_details.',
      'listing_agreement_details',
      'add_pid_notice',
      null::text
    ),
    (
      'listing_add_hoa_request',
      'listing_add_hoa_request',
      'Add HOA Request',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include HOA request from listing_agreement_details.',
      'listing_agreement_details',
      'add_hoa_request',
      null::text
    ),
    (
      'listing_add_mortgage_info_request',
      'listing_add_mortgage_info_request',
      'Add Mortgage Info Request',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include mortgage info request from listing_agreement_details.',
      'listing_agreement_details',
      'add_mortgage_info_request',
      null::text
    ),
    (
      'listing_add_mineral_info',
      'listing_add_mineral_info',
      'Add Mineral Info',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include mineral info addendum from listing_agreement_details.',
      'listing_agreement_details',
      'add_mineral_info',
      null::text
    ),
    (
      'listing_add_onsite_sewer_info',
      'listing_add_onsite_sewer_info',
      'Add Onsite Sewer Info',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include onsite sewer info from listing_agreement_details.',
      'listing_agreement_details',
      'add_onsite_sewer_info',
      null::text
    ),
    (
      'listing_add_property_insurance',
      'listing_add_property_insurance',
      'Add Property Insurance',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include property insurance addendum from listing_agreement_details.',
      'listing_agreement_details',
      'add_property_insurance',
      null::text
    ),
    (
      'listing_add_flood_hazard',
      'listing_add_flood_hazard',
      'Add Flood Hazard',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include flood hazard addendum from listing_agreement_details.',
      'listing_agreement_details',
      'add_flood_hazard',
      null::text
    ),
    (
      'listing_add_condo_addendum',
      'listing_add_condo_addendum',
      'Add Condo Addendum',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include condo addendum from listing_agreement_details.',
      'listing_agreement_details',
      'add_condo_addendum',
      null::text
    ),
    (
      'listing_add_keybox_tenant',
      'listing_add_keybox_tenant',
      'Add Keybox Tenant',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include keybox tenant addendum from listing_agreement_details.',
      'listing_agreement_details',
      'add_keybox_tenant',
      null::text
    ),
    (
      'listing_add_authorization_to_advertise',
      'listing_add_authorization_to_advertise',
      'Add Authorization to Advertise',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include authorization to advertise from listing_agreement_details.',
      'listing_agreement_details',
      'add_authorization_to_advertise',
      null::text
    ),
    (
      'listing_add_other_document',
      'listing_add_other_document',
      'Add Other Document',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Include other document from listing_agreement_details.',
      'listing_agreement_details',
      'add_other_document',
      null::text
    ),
    (
      'listing_add_other_document_description',
      'listing_add_other_document_description',
      'Other Document Description',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1101 Residential Real Estate Listing Agreement · Other document description from listing_agreement_details.',
      'listing_agreement_details',
      'add_other_document_description',
      null::text
    )
),
inserted as (
  insert into public.fields (
    field_key,
    field_name,
    field_label,
    field_data_type,
    field_widget_type,
    default_value,
    default_checked,
    required,
    notes,
    source_type,
    source_path,
    resolver_key
  )
  select
    s.field_key,
    s.field_name,
    s.field_label,
    s.field_data_type,
    s.field_widget_type,
    s.default_value,
    s.default_checked,
    s.required,
    s.notes,
    s.source_type,
    s.source_path,
    s.resolver_key
  from seed s
  where not exists (
    select 1
    from public.fields existing
    where lower(existing.field_key) = lower(s.field_key)
      and existing.status = 'ACTIVE'
  )
  returning field_key
)
update public.fields target
set
  field_name = s.field_name,
  field_label = s.field_label,
  field_data_type = s.field_data_type,
  field_widget_type = s.field_widget_type,
  default_value = s.default_value,
  default_checked = s.default_checked,
  required = s.required,
  notes = s.notes,
  source_type = s.source_type,
  source_path = s.source_path,
  resolver_key = s.resolver_key,
  update_date = now()
from seed s
where lower(target.field_key) = lower(s.field_key)
  and target.status = 'ACTIVE';
