-- Phase B: Storage path migration ledger.
-- Tracks copy/verify/DB-update operations for form-templates and generated-documents.
-- Does NOT change Storage policies.
-- Does NOT change business-table RLS.
-- Does NOT delete Storage objects.

begin;

create table if not exists public.storage_path_migrations (
  id bigint generated by default as identity primary key,
  create_date timestamptz not null default now(),
  update_date timestamptz not null default now(),
  status varchar(20) not null default 'ACTIVE',

  bucket_name text not null,
  entity_type text not null,
  entity_id bigint not null,
  old_path text not null,
  new_path text not null,
  source_size bigint,
  destination_size bigint,
  source_checksum text,
  destination_checksum text,
  migration_state text not null default 'PENDING',
  error_message text,
  copied_at timestamptz,
  verified_at timestamptz,
  database_updated_at timestamptz,
  rollback_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,

  constraint storage_path_migrations_status_check
    check (status in ('ACTIVE', 'INACTIVE', 'DELETED')),
  constraint storage_path_migrations_entity_type_check
    check (entity_type in ('FORM', 'PACKET_FORM')),
  constraint storage_path_migrations_bucket_check
    check (bucket_name in ('form-templates', 'generated-documents')),
  constraint storage_path_migrations_state_check
    check (migration_state in (
      'PENDING',
      'COPIED',
      'VERIFIED',
      'DB_UPDATED',
      'FAILED',
      'ROLLED_BACK'
    )),
  constraint storage_path_migrations_old_path_not_blank
    check (length(trim(old_path)) > 0),
  constraint storage_path_migrations_new_path_not_blank
    check (length(trim(new_path)) > 0),
  constraint storage_path_migrations_paths_distinct
    check (trim(old_path) <> trim(new_path))
);

comment on table public.storage_path_migrations is
  'Phase B operational ledger for Storage path copies. Not for end-user UI.';

create index if not exists storage_path_migrations_status_idx
  on public.storage_path_migrations (status);

create index if not exists storage_path_migrations_state_idx
  on public.storage_path_migrations (migration_state)
  where status = 'ACTIVE';

create index if not exists storage_path_migrations_entity_idx
  on public.storage_path_migrations (entity_type, entity_id)
  where status = 'ACTIVE';

create index if not exists storage_path_migrations_bucket_new_path_idx
  on public.storage_path_migrations (bucket_name, new_path)
  where status = 'ACTIVE';

create unique index if not exists storage_path_migrations_active_unique_uidx
  on public.storage_path_migrations (
    bucket_name,
    entity_type,
    entity_id,
    old_path,
    new_path
  )
  where status = 'ACTIVE';

drop trigger if exists storage_path_migrations_set_update_date
  on public.storage_path_migrations;
create trigger storage_path_migrations_set_update_date
before update on public.storage_path_migrations
for each row execute function public.set_update_date();

alter table public.storage_path_migrations enable row level security;

revoke all on table public.storage_path_migrations from anon;
revoke all on table public.storage_path_migrations from authenticated;

-- Dual-read helpers may look up legacy/new path mappings during Phase B.
grant select on table public.storage_path_migrations to authenticated;

-- Admin UI/ops (not built in Phase B) may manage ledger rows.
grant select, insert, update, delete on table public.storage_path_migrations to authenticated;
grant usage, select on sequence public.storage_path_migrations_id_seq to authenticated;

drop policy if exists "storage_path_migrations_authenticated_select"
  on public.storage_path_migrations;
create policy "storage_path_migrations_authenticated_select"
  on public.storage_path_migrations
  for select
  to authenticated
  using (status = 'ACTIVE');

drop policy if exists "storage_path_migrations_admin_all"
  on public.storage_path_migrations;
create policy "storage_path_migrations_admin_all"
  on public.storage_path_migrations
  for all
  to authenticated
  using (public.is_app_admin())
  with check (public.is_app_admin());

comment on policy "storage_path_migrations_authenticated_select"
  on public.storage_path_migrations is
  'TEMPORARY Phase B: authenticated dual-read may resolve legacy/new Storage path mappings.';

comment on policy "storage_path_migrations_admin_all"
  on public.storage_path_migrations is
  'Admin-only writes/management for the Storage migration ledger.';

commit;
