-- TXR-2001 (01-05-26) Residential Lease field catalog and first-pass flat-PDF mappings.
-- Form-owned fields (txr_2001_*). Does not create shared global reusable catalog fields.

-- ---------------------------------------------------------------------------
-- Ensure TXR-2001 form template exists (idempotent)
-- ---------------------------------------------------------------------------

insert into public.forms (
  form_code,
  form_name,
  form_category,
  state_code,
  version_label,
  source_storage_path,
  description,
  status
)
select
  'TXR-2001',
  'TXR-2001 Residential Lease',
  'CONTRACT',
  'TX',
  '01-05-26',
  'TXR-2001/ResidentialLease.pdf',
  'Texas REALTORS residential lease agreement (flat PDF, no AcroForm fields).',
  'ACTIVE'
where not exists (
  select 1
  from public.forms existing
  where existing.status = 'ACTIVE'
    and (
      lower(trim(existing.form_code)) in ('txr-2001', 'txr_2001')
      or lower(trim(existing.form_code)) like '%txr-2001%'
      or lower(trim(existing.form_code)) like '%txr_2001%'
    )
);

-- ---------------------------------------------------------------------------
-- Resolve TXR-2001 form
-- ---------------------------------------------------------------------------

create temp table txr_2001_form on commit drop as
select f.id as form_id
from public.forms f
where f.status = 'ACTIVE'
  and (
    lower(trim(f.form_code)) in ('txr-2001', 'txr_2001')
    or lower(trim(f.form_code)) like '%txr-2001%'
    or lower(trim(f.form_code)) like '%txr_2001%'
    or (
      lower(f.form_name) like '%residential%'
      and lower(f.form_name) like '%lease%'
      and lower(f.form_name) not like '%listing%'
      and lower(f.form_name) not like '%application%'
      and lower(f.form_name) not like '%guaranty%'
    )
  )
order by
  case when lower(trim(f.form_code)) in ('txr-2001', 'txr_2001') then 0 else 1 end,
  case
    when lower(f.form_name) like '%txr-2001%' or lower(f.form_name) like '%2001%' then 0
    else 1
  end,
  f.id
limit 1;

-- ---------------------------------------------------------------------------
-- Upsert field definitions (idempotent by field_key)
-- ---------------------------------------------------------------------------

create temp table txr_2001_fields_touched (
  field_key text primary key,
  action text not null
) on commit drop;

with field_seed (
  field_key,
  field_name,
  field_label,
  field_data_type,
  field_widget_type,
  default_value,
  default_checked,
  required,
  notes,
  source_type,
  source_path,
  resolver_key
) as (
  values
    (
      'txr_2001_landlord_name',
      'txr_2001_landlord_name',
      'Landlord owner name',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶1 · Landlord owner name',
      'packet_contact',
      'landlord_1.full_name',
      null::text
    ),
    (
      'txr_2001_tenant_names',
      'txr_2001_tenant_names',
      'Tenant names',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶1 · Tenant names',
      'packet_contact',
      'tenant_1.full_name',
      null::text
    ),
    (
      'txr_2001_occupants_names_dob',
      'txr_2001_occupants_names_dob',
      'Occupants names and DOB',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶1 · Occupants names and DOB',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_property_address',
      'txr_2001_property_address',
      'Property address',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶2 · Property address',
      'packet_property',
      'full_address',
      null::text
    ),
    (
      'txr_2001_property_legal_description',
      'txr_2001_property_legal_description',
      'Legal description',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶2 · Legal description',
      'packet_property',
      'legal_description',
      null::text
    ),
    (
      'txr_2001_property_county',
      'txr_2001_property_county',
      'County',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶2 · County',
      'packet_property',
      'county',
      null::text
    ),
    (
      'txr_2001_non_real_property_items',
      'txr_2001_non_real_property_items',
      'Non-real-property items',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶2 · Non-real-property items',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_commencement_date',
      'txr_2001_commencement_date',
      'Lease start date',
      'date',
      'date',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3A · Lease start date',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_expiration_date',
      'txr_2001_expiration_date',
      'Lease end date',
      'date',
      'date',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3A · Lease end date',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_termination_notice_days_before_expiration',
      'txr_2001_termination_notice_days_before_expiration',
      'Written notice days',
      'number',
      'number',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3A · Written notice days',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_monthly_base_rent',
      'txr_2001_monthly_base_rent',
      'Monthly rent amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3B · Monthly rent amount',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_first_month_rent_payable_to_landlord',
      'txr_2001_first_month_rent_payable_to_landlord',
      'First month rent payable to Landlord',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶3C · First month rent payable to Landlord',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_first_month_rent_payable_to_listing_broker',
      'txr_2001_first_month_rent_payable_to_listing_broker',
      'First month rent payable to Listing Broker',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶3C · First month rent payable to Listing Broker',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_first_month_rent_payable_to_property_manager',
      'txr_2001_first_month_rent_payable_to_property_manager',
      'First month rent payable to Property Manager',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶3C · First month rent payable to Property Manager',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_first_month_rent_due_date',
      'txr_2001_first_month_rent_due_date',
      'Due on or before',
      'date',
      'date',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3C · Due on or before',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_prorated_rent_amount',
      'txr_2001_prorated_rent_amount',
      'Prorated rent amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3D · Prorated rent amount',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_prorated_rent_due_date',
      'txr_2001_prorated_rent_due_date',
      'Prorated rent due date',
      'date',
      'date',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3D · Prorated rent due date',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_security_deposit_due_on_execution',
      'txr_2001_security_deposit_due_on_execution',
      'Security deposit due on execution',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶3E · Security deposit due on execution',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_security_deposit_due_on_date_checked',
      'txr_2001_security_deposit_due_on_date_checked',
      'Security deposit due on stated date',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶3E · Security deposit due on stated date',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_security_deposit_due_date',
      'txr_2001_security_deposit_due_date',
      'Security deposit date',
      'date',
      'date',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3E · Security deposit date',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_security_deposit_amount',
      'txr_2001_security_deposit_amount',
      'Security deposit amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3E · Security deposit amount',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_fee_animal_checked',
      'txr_2001_additional_fee_animal_checked',
      'Animal monthly fee selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶3F · Animal monthly fee selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_fee_animal_amount',
      'txr_2001_additional_fee_animal_amount',
      'Animal monthly fee',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3F · Animal monthly fee',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_fee_benefit_package_checked',
      'txr_2001_additional_fee_benefit_package_checked',
      'Benefit package selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶3F · Benefit package selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_fee_benefit_package_amount',
      'txr_2001_additional_fee_benefit_package_amount',
      'Benefit package amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3F · Benefit package amount',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_fee_custom_1_checked',
      'txr_2001_additional_fee_custom_1_checked',
      'Custom fee 1 selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶3F · Custom fee 1 selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_fee_custom_1_label',
      'txr_2001_additional_fee_custom_1_label',
      'Custom fee 1 label',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3F · Custom fee 1 label',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_fee_custom_1_amount',
      'txr_2001_additional_fee_custom_1_amount',
      'Custom fee 1 amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3F · Custom fee 1 amount',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_fee_custom_2_checked',
      'txr_2001_additional_fee_custom_2_checked',
      'Custom fee 2 selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶3F · Custom fee 2 selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_fee_custom_2_label',
      'txr_2001_additional_fee_custom_2_label',
      'Custom fee 2 label',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3F · Custom fee 2 label',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_fee_custom_2_amount',
      'txr_2001_additional_fee_custom_2_amount',
      'Custom fee 2 amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3F · Custom fee 2 amount',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_fee_custom_3_checked',
      'txr_2001_additional_fee_custom_3_checked',
      'Custom fee 3 selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶3F · Custom fee 3 selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_fee_custom_3_label',
      'txr_2001_additional_fee_custom_3_label',
      'Custom fee 3 label',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3F · Custom fee 3 label',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_fee_custom_3_amount',
      'txr_2001_additional_fee_custom_3_amount',
      'Custom fee 3 amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶3F · Custom fee 3 amount',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_rent_due_first_day',
      'txr_2001_rent_due_first_day',
      'Rent due first day of month',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4A · Rent due first day of month',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_rent_due_other_checked',
      'txr_2001_rent_due_other_checked',
      'Other rent due date selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4A · Other rent due date selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_rent_due_other_text',
      'txr_2001_rent_due_other_text',
      'Other rent due date/details',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶4A · Other rent due date/details',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_payment_recipient_name',
      'txr_2001_payment_recipient_name',
      'Payment recipient name',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶4B · Payment recipient name',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_payment_place',
      'txr_2001_payment_place',
      'Place of payment',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶4B · Place of payment',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_requires_single_monthly_payment',
      'txr_2001_requires_single_monthly_payment',
      'Requires one payment',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · Requires one payment',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_does_not_require_single_monthly_payment',
      'txr_2001_does_not_require_single_monthly_payment',
      'Does not require one payment',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · Does not require one payment',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_payment_method_cashiers_check',
      'txr_2001_payment_method_cashiers_check',
      'Payment method',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · Payment method',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_payment_method_electronic_payment',
      'txr_2001_payment_method_electronic_payment',
      'Payment method',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · Payment method',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_payment_method_money_order',
      'txr_2001_payment_method_money_order',
      'Payment method',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · Payment method',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_payment_method_personal_check',
      'txr_2001_payment_method_personal_check',
      'Payment method',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · Payment method',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_payment_method_other',
      'txr_2001_payment_method_other',
      'Other payment method',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · Other payment method',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_processing_fee_may_charge',
      'txr_2001_processing_fee_may_charge',
      'May charge processing fee',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · May charge processing fee',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_processing_fee_may_not_charge',
      'txr_2001_processing_fee_may_not_charge',
      'May not charge processing fee',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · May not charge processing fee',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_processing_fee_cashiers_check',
      'txr_2001_processing_fee_cashiers_check',
      'Processing fee method',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · Processing fee method',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_processing_fee_electronic_payment',
      'txr_2001_processing_fee_electronic_payment',
      'Processing fee method',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · Processing fee method',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_processing_fee_money_order',
      'txr_2001_processing_fee_money_order',
      'Processing fee method',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · Processing fee method',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_processing_fee_personal_check',
      'txr_2001_processing_fee_personal_check',
      'Processing fee method',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · Processing fee method',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_processing_fee_other',
      'txr_2001_processing_fee_other',
      'Processing fee method',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4C · Processing fee method',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_late_fee_due_day',
      'txr_2001_late_fee_due_day',
      'Day of month rent must be received',
      'number',
      'number',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶4E · Day of month rent must be received',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_initial_late_fee_amount_checked',
      'txr_2001_initial_late_fee_amount_checked',
      'Initial late fee amount selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4E · Initial late fee amount selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_initial_late_fee_amount',
      'txr_2001_initial_late_fee_amount',
      'Initial late fee amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶4E · Initial late fee amount',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_initial_late_fee_percent_checked',
      'txr_2001_initial_late_fee_percent_checked',
      'Initial late fee percent selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4E · Initial late fee percent selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_initial_late_fee_percent',
      'txr_2001_initial_late_fee_percent',
      'Initial late fee percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶4E · Initial late fee percent',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_late_fee_amount_checked',
      'txr_2001_additional_late_fee_amount_checked',
      'Additional late fee amount selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4E · Additional late fee amount selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_late_fee_amount',
      'txr_2001_additional_late_fee_amount',
      'Additional daily late fee amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶4E · Additional daily late fee amount',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_late_fee_percent_checked',
      'txr_2001_additional_late_fee_percent_checked',
      'Additional late fee percent selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶4E · Additional late fee percent selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_additional_late_fee_percent',
      'txr_2001_additional_late_fee_percent',
      'Additional daily late fee percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶4E · Additional daily late fee percent',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_returned_payment_fee',
      'txr_2001_returned_payment_fee',
      'Returned payment fee',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶4F · Returned payment fee',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_auto_renewal_notice_30_days',
      'txr_2001_auto_renewal_notice_30_days',
      '30 days before expiration',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶5A · 30 days before expiration',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_auto_renewal_notice_other_days_checked',
      'txr_2001_auto_renewal_notice_other_days_checked',
      'Other notice period selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶5A · Other notice period selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_auto_renewal_notice_other_days',
      'txr_2001_auto_renewal_notice_other_days',
      'Other days before expiration',
      'number',
      'number',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶5A · Other days before expiration',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_month_to_month_termination_last_day_next_month',
      'txr_2001_month_to_month_termination_last_day_next_month',
      'Termination effective last day of following month',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶5B · Termination effective last day of following month',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_month_to_month_termination_designated_date',
      'txr_2001_month_to_month_termination_designated_date',
      'Termination effective designated date',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶5B · Termination effective designated date',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_unauthorized_animal_initial_charge',
      'txr_2001_unauthorized_animal_initial_charge',
      'Unauthorized animal initial charge',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶6B · Unauthorized animal initial charge',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_unauthorized_animal_daily_charge',
      'txr_2001_unauthorized_animal_daily_charge',
      'Unauthorized animal daily charge',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶6B · Unauthorized animal daily charge',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_utilities_landlord_pays',
      'txr_2001_utilities_landlord_pays',
      'Utilities paid by Landlord',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶8A · Utilities paid by Landlord',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_property_is_part_of_hoa',
      'txr_2001_property_is_part_of_hoa',
      'HOA yes',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶9B · HOA yes',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_property_is_not_part_of_hoa',
      'txr_2001_property_is_not_part_of_hoa',
      'HOA no',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶9B · HOA no',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_hoa_name',
      'txr_2001_hoa_name',
      'HOA name if any',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶9B · HOA name if any',
      'packet_property',
      'hoa_name',
      null::text
    ),
    (
      'txr_2001_guest_consecutive_day_limit',
      'txr_2001_guest_consecutive_day_limit',
      'Consecutive guest days',
      'number',
      'number',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶9D · Consecutive guest days',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_vehicle_limit',
      'txr_2001_vehicle_limit',
      'Max vehicles',
      'number',
      'number',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶10 · Max vehicles',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_access_trip_charge',
      'txr_2001_access_trip_charge',
      'Access trip charge',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶11C · Access trip charge',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_keybox_authorized_last_days',
      'txr_2001_keybox_authorized_last_days',
      'Keybox allowed during last X days',
      'number',
      'number',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶11D · Keybox allowed during last X days',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_keybox_withdrawal_fee',
      'txr_2001_keybox_withdrawal_fee',
      'Fee to withdraw keybox authorization',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶11D · Fee to withdraw keybox authorization',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_move_in_landlord_conditions',
      'txr_2001_move_in_landlord_conditions',
      'Landlord move-in conditions',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶12B · Landlord move-in conditions',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_inventory_condition_due_days',
      'txr_2001_inventory_condition_due_days',
      'Days to deliver inventory/condition form',
      'number',
      'number',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶12C · Days to deliver inventory/condition form',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_yard_watering_times',
      'txr_2001_yard_watering_times',
      'Yard watering times',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶14B · Yard watering times',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_yard_maintained_by_landlord',
      'txr_2001_yard_maintained_by_landlord',
      'Landlord maintains yard',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶14B · Landlord maintains yard',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_yard_maintained_by_tenant',
      'txr_2001_yard_maintained_by_tenant',
      'Tenant maintains yard',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶14B · Tenant maintains yard',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_yard_maintenance_contract_required',
      'txr_2001_yard_maintenance_contract_required',
      'Tenant maintains scheduled yard contract',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶14B · Tenant maintains scheduled yard contract',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_yard_maintenance_contract_regular_contractor',
      'txr_2001_yard_maintenance_contract_regular_contractor',
      'Regular contractor',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶14B · Regular contractor',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_yard_maintenance_contract_other_checked',
      'txr_2001_yard_maintenance_contract_other_checked',
      'Other contractor selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶14B · Other contractor selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_yard_maintenance_contract_other',
      'txr_2001_yard_maintenance_contract_other',
      'Other contractor name/details',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶14B · Other contractor name/details',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_smoking_permitted',
      'txr_2001_smoking_permitted',
      'Smoking permitted',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶14F · Smoking permitted',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_smoking_not_permitted',
      'txr_2001_smoking_not_permitted',
      'Smoking not permitted',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶14F · Smoking not permitted',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_emergency_repair_phone',
      'txr_2001_emergency_repair_phone',
      'Emergency repair phone',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶15A · Emergency repair phone',
      'packet_contact',
      'landlord_1.phone',
      null::text
    ),
    (
      'txr_2001_tenant_specific_repair_items',
      'txr_2001_tenant_specific_repair_items',
      'Specific items/appliances tenant pays to repair',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶15D · Specific items/appliances tenant pays to repair',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_special_provisions',
      'txr_2001_special_provisions',
      'Special provisions',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶23 · Special provisions',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_replacement_tenant_fee_tenant_procures_amount_checked',
      'txr_2001_replacement_tenant_fee_tenant_procures_amount_checked',
      'Tenant procures replacement - flat fee selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶25B · Tenant procures replacement - flat fee selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_replacement_tenant_fee_tenant_procures_amount',
      'txr_2001_replacement_tenant_fee_tenant_procures_amount',
      'Tenant procures replacement flat fee',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶25B · Tenant procures replacement flat fee',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_replacement_tenant_fee_tenant_procures_percent_checked',
      'txr_2001_replacement_tenant_fee_tenant_procures_percent_checked',
      'Tenant procures replacement - percent selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶25B · Tenant procures replacement - percent selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_replacement_tenant_fee_tenant_procures_percent',
      'txr_2001_replacement_tenant_fee_tenant_procures_percent',
      'Tenant procures replacement percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶25B · Tenant procures replacement percent',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_replacement_tenant_fee_landlord_procures_amount_checked',
      'txr_2001_replacement_tenant_fee_landlord_procures_amount_checked',
      'Landlord procures replacement - flat fee selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶25B · Landlord procures replacement - flat fee selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_replacement_tenant_fee_landlord_procures_amount',
      'txr_2001_replacement_tenant_fee_landlord_procures_amount',
      'Landlord procures replacement flat fee',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶25B · Landlord procures replacement flat fee',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_replacement_tenant_fee_landlord_procures_percent_checked',
      'txr_2001_replacement_tenant_fee_landlord_procures_percent_checked',
      'Landlord procures replacement - percent selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶25B · Landlord procures replacement - percent selected',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_replacement_tenant_fee_landlord_procures_percent',
      'txr_2001_replacement_tenant_fee_landlord_procures_percent',
      'Landlord procures replacement percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶25B · Landlord procures replacement percent',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_rental_flood_disclosure',
      'txr_2001_addendum_rental_flood_disclosure',
      'TXR 2015',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · TXR 2015',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_agreement_between_brokers',
      'txr_2001_addendum_agreement_between_brokers',
      'TXR 2002',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · TXR 2002',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_lead_based_paint',
      'txr_2001_addendum_lead_based_paint',
      'TXR 2008',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · TXR 2008',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_bed_bug',
      'txr_2001_addendum_bed_bug',
      'TXR 2013',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · TXR 2013',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_inventory_condition_form',
      'txr_2001_addendum_inventory_condition_form',
      'TXR 2207',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · TXR 2207',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_residential_lease_application',
      'txr_2001_addendum_residential_lease_application',
      'TXR 2003',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · TXR 2003',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_pool_spa',
      'txr_2001_addendum_pool_spa',
      'TXR 2010',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · TXR 2010',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_residential_lease_guaranty',
      'txr_2001_addendum_residential_lease_guaranty',
      'TXR 2007',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · TXR 2007',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_animal_agreement',
      'txr_2001_addendum_animal_agreement',
      'TXR 2004',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · TXR 2004',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_mold_remediation_consumer_protection',
      'txr_2001_addendum_mold_remediation_consumer_protection',
      'TXR 2507',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · TXR 2507',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_custom_1_checked',
      'txr_2001_addendum_custom_1_checked',
      'Custom addendum',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · Custom addendum',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_custom_1_text',
      'txr_2001_addendum_custom_1_text',
      'Custom addendum left',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶28 · Custom addendum left',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_custom_2_checked',
      'txr_2001_addendum_custom_2_checked',
      'Custom addendum',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · Custom addendum',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_custom_2_text',
      'txr_2001_addendum_custom_2_text',
      'Custom addendum right',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶28 · Custom addendum right',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_custom_3_checked',
      'txr_2001_addendum_custom_3_checked',
      'Custom addendum',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · Custom addendum',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_custom_3_text',
      'txr_2001_addendum_custom_3_text',
      'Custom addendum left',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶28 · Custom addendum left',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_custom_4_checked',
      'txr_2001_addendum_custom_4_checked',
      'Custom addendum',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶28 · Custom addendum',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_addendum_custom_4_text',
      'txr_2001_addendum_custom_4_text',
      'Custom addendum right',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶28 · Custom addendum right',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_tenant_notice_email',
      'txr_2001_tenant_notice_email',
      'Tenant email for notices',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶29 · Tenant email for notices',
      'packet_contact',
      'tenant_1.email',
      null::text
    ),
    (
      'txr_2001_landlord_notice_email',
      'txr_2001_landlord_notice_email',
      'Landlord email for notices',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶29 · Landlord email for notices',
      'packet_contact',
      'landlord_1.email',
      null::text
    ),
    (
      'txr_2001_deceased_tenant_contact_name',
      'txr_2001_deceased_tenant_contact_name',
      'Non-tenant emergency/death contact',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶31F · Non-tenant emergency/death contact',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_deceased_tenant_contact_phone',
      'txr_2001_deceased_tenant_contact_phone',
      'Contact phone',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶31F · Contact phone',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_deceased_tenant_contact_address',
      'txr_2001_deceased_tenant_contact_address',
      'Contact address',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶31F · Contact address',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_deceased_tenant_contact_email',
      'txr_2001_deceased_tenant_contact_email',
      'Contact email',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶31F · Contact email',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_liability_insurance_required_yes',
      'txr_2001_liability_insurance_required_yes',
      'Landlord requires liability insurance',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶31I · Landlord requires liability insurance',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_liability_insurance_required_no',
      'txr_2001_liability_insurance_required_no',
      'Landlord does not require liability insurance',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶31I · Landlord does not require liability insurance',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_liability_insurance_minimum_amount',
      'txr_2001_liability_insurance_minimum_amount',
      'Minimum liability insurance',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶31I · Minimum liability insurance',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_landlord_broker_name',
      'txr_2001_landlord_broker_name',
      'Landlord broker name',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶31J · Landlord broker name',
      'settings_brokerage',
      'broker_full_name',
      null::text
    ),
    (
      'txr_2001_landlord_broker_will_manage',
      'txr_2001_landlord_broker_will_manage',
      'Broker will manage',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶31J · Broker will manage',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_landlord_broker_will_not_manage',
      'txr_2001_landlord_broker_will_not_manage',
      'Broker will not manage',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶31J · Broker will not manage',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_managed_by_landlord',
      'txr_2001_managed_by_landlord',
      'Property managed by Landlord',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶31J · Property managed by Landlord',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_managed_by_property_manager',
      'txr_2001_managed_by_property_manager',
      'Property managed by Property Manager',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶31J · Property managed by Property Manager',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_property_manager_name',
      'txr_2001_property_manager_name',
      'Property manager name',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶31J · Property manager name',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_property_manager_phone',
      'txr_2001_property_manager_phone',
      'Property manager phone',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶31J · Property manager phone',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_property_manager_address',
      'txr_2001_property_manager_address',
      'Property manager address',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶31J · Property manager address',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_property_manager_email',
      'txr_2001_property_manager_email',
      'Property manager email',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶31J · Property manager email',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_landlord_copy_provided_date',
      'txr_2001_landlord_copy_provided_date',
      'Landlord copy provided date',
      'date',
      'date',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶Landlord Use · Landlord copy provided date',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_landlord_copy_provided_to_tenant',
      'txr_2001_landlord_copy_provided_to_tenant',
      'Tenant who received copy',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-2001 ¶Landlord Use · Tenant who received copy',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_copy_delivery_mail',
      'txr_2001_copy_delivery_mail',
      'Copy delivered by mail',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶Landlord Use · Copy delivered by mail',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_copy_delivery_email',
      'txr_2001_copy_delivery_email',
      'Copy delivered by email',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶Landlord Use · Copy delivered by email',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'txr_2001_copy_delivery_in_person',
      'txr_2001_copy_delivery_in_person',
      'Copy delivered in person',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-2001 ¶Landlord Use · Copy delivered in person',
      'manual_only',
      null::text,
      null::text
    )
),
inserted_fields as (
  insert into public.fields (
    field_key,
    field_name,
    field_label,
    field_data_type,
    field_widget_type,
    default_value,
    default_checked,
    required,
    notes,
    source_type,
    source_path,
    resolver_key,
    status
  )
  select
    s.field_key,
    s.field_name,
    s.field_label,
    s.field_data_type,
    s.field_widget_type,
    s.default_value,
    s.default_checked,
    s.required,
    s.notes,
    s.source_type,
    s.source_path,
    s.resolver_key,
    'ACTIVE'
  from field_seed s
  where not exists (
    select 1
    from public.fields existing
    where lower(existing.field_key) = lower(s.field_key)
      and existing.status = 'ACTIVE'
  )
  returning field_key
),
updated_fields as (
  update public.fields target
  set
    field_name = s.field_name,
    field_label = s.field_label,
    field_data_type = s.field_data_type,
    field_widget_type = s.field_widget_type,
    default_value = s.default_value,
    default_checked = s.default_checked,
    required = s.required,
    notes = s.notes,
    source_type = s.source_type,
    source_path = s.source_path,
    resolver_key = s.resolver_key,
    update_date = now()
  from field_seed s
  where lower(target.field_key) = lower(s.field_key)
    and target.status = 'ACTIVE'
  returning target.field_key
)
insert into txr_2001_fields_touched (field_key, action)
select field_key, 'inserted' from inserted_fields
union all
select field_key, 'updated' from updated_fields;

-- ---------------------------------------------------------------------------
-- Deactivate existing ACTIVE mappings for seeded field keys (TXR-2001 only)
-- ---------------------------------------------------------------------------

with mapping_field_keys(field_key) as (
  values
      ('txr_2001_landlord_name'),
      ('txr_2001_tenant_names'),
      ('txr_2001_occupants_names_dob'),
      ('txr_2001_property_address'),
      ('txr_2001_property_legal_description'),
      ('txr_2001_property_county'),
      ('txr_2001_non_real_property_items'),
      ('txr_2001_commencement_date'),
      ('txr_2001_expiration_date'),
      ('txr_2001_termination_notice_days_before_expiration'),
      ('txr_2001_monthly_base_rent'),
      ('txr_2001_first_month_rent_payable_to_landlord'),
      ('txr_2001_first_month_rent_payable_to_listing_broker'),
      ('txr_2001_first_month_rent_payable_to_property_manager'),
      ('txr_2001_first_month_rent_due_date'),
      ('txr_2001_prorated_rent_amount'),
      ('txr_2001_prorated_rent_due_date'),
      ('txr_2001_security_deposit_due_on_execution'),
      ('txr_2001_security_deposit_due_on_date_checked'),
      ('txr_2001_security_deposit_due_date'),
      ('txr_2001_security_deposit_amount'),
      ('txr_2001_additional_fee_animal_checked'),
      ('txr_2001_additional_fee_animal_amount'),
      ('txr_2001_additional_fee_benefit_package_checked'),
      ('txr_2001_additional_fee_benefit_package_amount'),
      ('txr_2001_additional_fee_custom_1_checked'),
      ('txr_2001_additional_fee_custom_1_label'),
      ('txr_2001_additional_fee_custom_1_amount'),
      ('txr_2001_additional_fee_custom_2_checked'),
      ('txr_2001_additional_fee_custom_2_label'),
      ('txr_2001_additional_fee_custom_2_amount'),
      ('txr_2001_additional_fee_custom_3_checked'),
      ('txr_2001_additional_fee_custom_3_label'),
      ('txr_2001_additional_fee_custom_3_amount'),
      ('txr_2001_rent_due_first_day'),
      ('txr_2001_rent_due_other_checked'),
      ('txr_2001_rent_due_other_text'),
      ('txr_2001_payment_recipient_name'),
      ('txr_2001_payment_place'),
      ('txr_2001_requires_single_monthly_payment'),
      ('txr_2001_does_not_require_single_monthly_payment'),
      ('txr_2001_payment_method_cashiers_check'),
      ('txr_2001_payment_method_electronic_payment'),
      ('txr_2001_payment_method_money_order'),
      ('txr_2001_payment_method_personal_check'),
      ('txr_2001_payment_method_other'),
      ('txr_2001_processing_fee_may_charge'),
      ('txr_2001_processing_fee_may_not_charge'),
      ('txr_2001_processing_fee_cashiers_check'),
      ('txr_2001_processing_fee_electronic_payment'),
      ('txr_2001_processing_fee_money_order'),
      ('txr_2001_processing_fee_personal_check'),
      ('txr_2001_processing_fee_other'),
      ('txr_2001_late_fee_due_day'),
      ('txr_2001_initial_late_fee_amount_checked'),
      ('txr_2001_initial_late_fee_amount'),
      ('txr_2001_initial_late_fee_percent_checked'),
      ('txr_2001_initial_late_fee_percent'),
      ('txr_2001_additional_late_fee_amount_checked'),
      ('txr_2001_additional_late_fee_amount'),
      ('txr_2001_additional_late_fee_percent_checked'),
      ('txr_2001_additional_late_fee_percent'),
      ('txr_2001_returned_payment_fee'),
      ('txr_2001_auto_renewal_notice_30_days'),
      ('txr_2001_auto_renewal_notice_other_days_checked'),
      ('txr_2001_auto_renewal_notice_other_days'),
      ('txr_2001_month_to_month_termination_last_day_next_month'),
      ('txr_2001_month_to_month_termination_designated_date'),
      ('txr_2001_unauthorized_animal_initial_charge'),
      ('txr_2001_unauthorized_animal_daily_charge'),
      ('txr_2001_utilities_landlord_pays'),
      ('txr_2001_property_is_part_of_hoa'),
      ('txr_2001_property_is_not_part_of_hoa'),
      ('txr_2001_hoa_name'),
      ('txr_2001_guest_consecutive_day_limit'),
      ('txr_2001_vehicle_limit'),
      ('txr_2001_access_trip_charge'),
      ('txr_2001_keybox_authorized_last_days'),
      ('txr_2001_keybox_withdrawal_fee'),
      ('txr_2001_move_in_landlord_conditions'),
      ('txr_2001_inventory_condition_due_days'),
      ('txr_2001_yard_watering_times'),
      ('txr_2001_yard_maintained_by_landlord'),
      ('txr_2001_yard_maintained_by_tenant'),
      ('txr_2001_yard_maintenance_contract_required'),
      ('txr_2001_yard_maintenance_contract_regular_contractor'),
      ('txr_2001_yard_maintenance_contract_other_checked'),
      ('txr_2001_yard_maintenance_contract_other'),
      ('txr_2001_smoking_permitted'),
      ('txr_2001_smoking_not_permitted'),
      ('txr_2001_emergency_repair_phone'),
      ('txr_2001_tenant_specific_repair_items'),
      ('txr_2001_special_provisions'),
      ('txr_2001_replacement_tenant_fee_tenant_procures_amount_checked'),
      ('txr_2001_replacement_tenant_fee_tenant_procures_amount'),
      ('txr_2001_replacement_tenant_fee_tenant_procures_percent_checked'),
      ('txr_2001_replacement_tenant_fee_tenant_procures_percent'),
      ('txr_2001_replacement_tenant_fee_landlord_procures_amount_checked'),
      ('txr_2001_replacement_tenant_fee_landlord_procures_amount'),
      ('txr_2001_replacement_tenant_fee_landlord_procures_percent_checked'),
      ('txr_2001_replacement_tenant_fee_landlord_procures_percent'),
      ('txr_2001_addendum_rental_flood_disclosure'),
      ('txr_2001_addendum_agreement_between_brokers'),
      ('txr_2001_addendum_lead_based_paint'),
      ('txr_2001_addendum_bed_bug'),
      ('txr_2001_addendum_inventory_condition_form'),
      ('txr_2001_addendum_residential_lease_application'),
      ('txr_2001_addendum_pool_spa'),
      ('txr_2001_addendum_residential_lease_guaranty'),
      ('txr_2001_addendum_animal_agreement'),
      ('txr_2001_addendum_mold_remediation_consumer_protection'),
      ('txr_2001_addendum_custom_1_checked'),
      ('txr_2001_addendum_custom_1_text'),
      ('txr_2001_addendum_custom_2_checked'),
      ('txr_2001_addendum_custom_2_text'),
      ('txr_2001_addendum_custom_3_checked'),
      ('txr_2001_addendum_custom_3_text'),
      ('txr_2001_addendum_custom_4_checked'),
      ('txr_2001_addendum_custom_4_text'),
      ('txr_2001_tenant_notice_email'),
      ('txr_2001_landlord_notice_email'),
      ('txr_2001_deceased_tenant_contact_name'),
      ('txr_2001_deceased_tenant_contact_phone'),
      ('txr_2001_deceased_tenant_contact_address'),
      ('txr_2001_deceased_tenant_contact_email'),
      ('txr_2001_liability_insurance_required_yes'),
      ('txr_2001_liability_insurance_required_no'),
      ('txr_2001_liability_insurance_minimum_amount'),
      ('txr_2001_landlord_broker_name'),
      ('txr_2001_landlord_broker_will_manage'),
      ('txr_2001_landlord_broker_will_not_manage'),
      ('txr_2001_managed_by_landlord'),
      ('txr_2001_managed_by_property_manager'),
      ('txr_2001_property_manager_name'),
      ('txr_2001_property_manager_phone'),
      ('txr_2001_property_manager_address'),
      ('txr_2001_property_manager_email'),
      ('txr_2001_landlord_copy_provided_date'),
      ('txr_2001_landlord_copy_provided_to_tenant'),
      ('txr_2001_copy_delivery_mail'),
      ('txr_2001_copy_delivery_email'),
      ('txr_2001_copy_delivery_in_person')
),
target_fields as (
  select fld.id as field_id
  from public.fields fld
  inner join mapping_field_keys mk
    on lower(fld.field_key) = lower(mk.field_key)
  where fld.status = 'ACTIVE'
)
update public.form_field_mappings ffm
set
  status = 'INACTIVE',
  update_date = now()
from txr_2001_form tf,
     target_fields fld
where ffm.form_id = tf.form_id
  and ffm.field_id = fld.field_id
  and ffm.status = 'ACTIVE';

-- ---------------------------------------------------------------------------
-- First-pass PDF mappings (manual/visual placement)
-- ---------------------------------------------------------------------------

create temp table txr_2001_placement_seed (
  field_key text not null,
  mapping_name text not null,
  occurrence_index integer,
  page_number integer not null,
  x numeric not null,
  y numeric not null,
  width numeric not null,
  height numeric not null,
  field_widget_type text not null
) on commit drop;

insert into txr_2001_placement_seed (
  field_key,
  mapping_name,
  occurrence_index,
  page_number,
  x,
  y,
  width,
  height,
  field_widget_type
)
values
  ('txr_2001_landlord_name', 'Page 1 ¶1 Landlord owner name', null::integer, 1, 254, 140, 322, 16, 'text'),
  ('txr_2001_tenant_names', 'Page 1 ¶1 Tenant names', null::integer, 1, 72, 153, 477, 16, 'text'),
  ('txr_2001_occupants_names_dob', 'Page 1 ¶1 Occupants names and DOB', null::integer, 1, 72, 178, 504, 48, 'text'),
  ('txr_2001_property_address', 'Page 1 ¶2 Property address', null::integer, 1, 126, 341, 450, 16, 'text'),
  ('txr_2001_property_legal_description', 'Page 1 ¶2 Legal description', null::integer, 1, 72, 354, 504, 56, 'text'),
  ('txr_2001_property_county', 'Page 1 ¶2 County', null::integer, 1, 72, 471, 67, 16, 'text'),
  ('txr_2001_non_real_property_items', 'Page 1 ¶2 Non-real-property items', null::integer, 1, 72, 537, 504, 56, 'text'),
  ('txr_2001_commencement_date', 'Page 1 ¶3A Lease start date', null::integer, 1, 188, 498, 136, 16, 'date'),
  ('txr_2001_expiration_date', 'Page 1 ¶3A Lease end date', null::integer, 1, 411, 498, 165, 16, 'date'),
  ('txr_2001_termination_notice_days_before_expiration', 'Page 1 ¶3A Written notice days', null::integer, 1, 72, 537, 93, 16, 'number'),
  ('txr_2001_monthly_base_rent', 'Page 1 ¶3B Monthly rent amount', null::integer, 1, 72, 564, 90, 16, 'text'),
  ('txr_2001_first_month_rent_payable_to_landlord', 'Page 1 ¶3C First month rent payable to Landlord', null::integer, 1, 426, 567, 10, 10, 'checkbox'),
  ('txr_2001_first_month_rent_payable_to_listing_broker', 'Page 1 ¶3C First month rent payable to Listing Broker', null::integer, 1, 496, 567, 10, 10, 'checkbox'),
  ('txr_2001_first_month_rent_payable_to_property_manager', 'Page 1 ¶3C First month rent payable to Property Manager', null::integer, 1, 85, 580, 10, 10, 'checkbox'),
  ('txr_2001_first_month_rent_due_date', 'Page 1 ¶3C Due on or before', null::integer, 1, 251, 577, 73, 16, 'date'),
  ('txr_2001_prorated_rent_amount', 'Page 1 ¶3D Prorated rent amount', null::integer, 1, 71, 604, 68, 16, 'text'),
  ('txr_2001_prorated_rent_due_date', 'Page 1 ¶3D Prorated rent due date', null::integer, 1, 68, 630, 80, 16, 'date'),
  ('txr_2001_security_deposit_due_on_execution', 'Page 1 ¶3E Security deposit due on execution', null::integer, 1, 223, 634, 10, 10, 'checkbox'),
  ('txr_2001_security_deposit_due_on_date_checked', 'Page 1 ¶3E Security deposit due on stated date', null::integer, 1, 362, 634, 10, 10, 'checkbox'),
  ('txr_2001_security_deposit_due_date', 'Page 1 ¶3E Security deposit date', null::integer, 1, 200, 643, 97, 16, 'date'),
  ('txr_2001_security_deposit_amount', 'Page 1 ¶3E Security deposit amount', null::integer, 1, 306, 669, 78, 16, 'text'),
  ('txr_2001_additional_fee_animal_checked', 'Page 1 ¶3F Animal monthly fee selected', null::integer, 1, 190, 671, 10, 10, 'checkbox'),
  ('txr_2001_additional_fee_animal_amount', 'Page 1 ¶3F Animal monthly fee', null::integer, 1, 211, 669, 34, 16, 'text'),
  ('txr_2001_additional_fee_benefit_package_checked', 'Page 1 ¶3F Benefit package selected', null::integer, 1, 285, 671, 10, 10, 'checkbox'),
  ('txr_2001_additional_fee_benefit_package_amount', 'Page 1 ¶3F Benefit package amount', null::integer, 1, 254, 669, 24, 16, 'text'),
  ('txr_2001_additional_fee_custom_1_checked', 'Page 1 ¶3F Custom fee 1 selected', null::integer, 1, 420, 671, 10, 10, 'checkbox'),
  ('txr_2001_additional_fee_custom_1_label', 'Page 1 ¶3F Custom fee 1 label', null::integer, 1, 306, 669, 78, 16, 'text'),
  ('txr_2001_additional_fee_custom_1_amount', 'Page 1 ¶3F Custom fee 1 amount', null::integer, 1, 378, 684, 21, 16, 'text'),
  ('txr_2001_additional_fee_custom_2_checked', 'Page 1 ¶3F Custom fee 2 selected', null::integer, 1, 68, 684, 10, 10, 'checkbox'),
  ('txr_2001_additional_fee_custom_2_label', 'Page 1 ¶3F Custom fee 2 label', null::integer, 1, 84, 682, 100, 16, 'text'),
  ('txr_2001_additional_fee_custom_2_amount', 'Page 1 ¶3F Custom fee 2 amount', null::integer, 1, 223, 684, 21, 16, 'text'),
  ('txr_2001_additional_fee_custom_3_checked', 'Page 1 ¶3F Custom fee 3 selected', null::integer, 1, 223, 684, 10, 10, 'checkbox'),
  ('txr_2001_additional_fee_custom_3_label', 'Page 1 ¶3F Custom fee 3 label', null::integer, 1, 254, 682, 80, 16, 'text'),
  ('txr_2001_additional_fee_custom_3_amount', 'Page 1 ¶3F Custom fee 3 amount', null::integer, 1, 378, 684, 21, 16, 'text'),
  ('txr_2001_rent_due_first_day', 'Page 2 ¶4A Rent due first day of month', null::integer, 2, 72, 188, 10, 10, 'checkbox'),
  ('txr_2001_rent_due_other_checked', 'Page 2 ¶4A Other rent due date selected', null::integer, 2, 86, 202, 10, 10, 'checkbox'),
  ('txr_2001_rent_due_other_text', 'Page 2 ¶4A Other rent due date/details', null::integer, 2, 125, 199, 452, 16, 'text'),
  ('txr_2001_payment_recipient_name', 'Page 2 ¶4B Payment recipient name', null::integer, 2, 72, 225, 87, 16, 'text'),
  ('txr_2001_payment_place', 'Page 2 ¶4B Place of payment', null::integer, 2, 144, 276, 396, 48, 'text'),
  ('txr_2001_requires_single_monthly_payment', 'Page 2 ¶4C Requires one payment', null::integer, 2, 141, 361, 10, 10, 'checkbox'),
  ('txr_2001_does_not_require_single_monthly_payment', 'Page 2 ¶4C Does not require one payment', null::integer, 2, 196, 361, 10, 10, 'checkbox'),
  ('txr_2001_payment_method_cashiers_check', 'Page 2 ¶4C Payment method', null::integer, 2, 230, 392, 10, 10, 'checkbox'),
  ('txr_2001_payment_method_electronic_payment', 'Page 2 ¶4C Payment method', null::integer, 2, 315, 392, 10, 10, 'checkbox'),
  ('txr_2001_payment_method_money_order', 'Page 2 ¶4C Payment method', null::integer, 2, 415, 392, 10, 10, 'checkbox'),
  ('txr_2001_payment_method_personal_check', 'Page 2 ¶4C Payment method', null::integer, 2, 487, 392, 10, 10, 'checkbox'),
  ('txr_2001_payment_method_other', 'Page 2 ¶4C Other payment method', null::integer, 2, 90, 405, 10, 10, 'checkbox'),
  ('txr_2001_processing_fee_may_charge', 'Page 2 ¶4C May charge processing fee', null::integer, 2, 134, 420, 10, 10, 'checkbox'),
  ('txr_2001_processing_fee_may_not_charge', 'Page 2 ¶4C May not charge processing fee', null::integer, 2, 181, 420, 10, 10, 'checkbox'),
  ('txr_2001_processing_fee_cashiers_check', 'Page 2 ¶4C Processing fee method', null::integer, 2, 397, 434, 10, 10, 'checkbox'),
  ('txr_2001_processing_fee_electronic_payment', 'Page 2 ¶4C Processing fee method', null::integer, 2, 482, 434, 10, 10, 'checkbox'),
  ('txr_2001_processing_fee_money_order', 'Page 2 ¶4C Processing fee method', null::integer, 2, 90, 447, 10, 10, 'checkbox'),
  ('txr_2001_processing_fee_personal_check', 'Page 2 ¶4C Processing fee method', null::integer, 2, 161, 447, 10, 10, 'checkbox'),
  ('txr_2001_processing_fee_other', 'Page 2 ¶4C Processing fee method', null::integer, 2, 254, 447, 10, 10, 'checkbox'),
  ('txr_2001_late_fee_due_day', 'Page 2 ¶4E Day of month rent must be received', null::integer, 2, 72, 526, 74, 16, 'number'),
  ('txr_2001_initial_late_fee_amount_checked', 'Page 2 ¶4E Initial late fee amount selected', null::integer, 2, 334, 634, 10, 10, 'checkbox'),
  ('txr_2001_initial_late_fee_amount', 'Page 2 ¶4E Initial late fee amount', null::integer, 2, 373, 631, 57, 16, 'text'),
  ('txr_2001_initial_late_fee_percent_checked', 'Page 2 ¶4E Initial late fee percent selected', null::integer, 2, 455, 634, 10, 10, 'checkbox'),
  ('txr_2001_initial_late_fee_percent', 'Page 2 ¶4E Initial late fee percent', null::integer, 2, 481, 631, 51, 16, 'text'),
  ('txr_2001_additional_late_fee_amount_checked', 'Page 2 ¶4E Additional late fee amount selected', null::integer, 2, 317, 660, 10, 10, 'checkbox'),
  ('txr_2001_additional_late_fee_amount', 'Page 2 ¶4E Additional daily late fee amount', null::integer, 2, 355, 658, 39, 16, 'text'),
  ('txr_2001_additional_late_fee_percent_checked', 'Page 2 ¶4E Additional late fee percent selected', null::integer, 2, 419, 660, 10, 10, 'checkbox'),
  ('txr_2001_additional_late_fee_percent', 'Page 2 ¶4E Additional daily late fee percent', null::integer, 2, 445, 658, 51, 16, 'text'),
  ('txr_2001_returned_payment_fee', 'Page 3 ¶4F Returned payment fee', null::integer, 3, 89, 56, 132, 16, 'text'),
  ('txr_2001_auto_renewal_notice_30_days', 'Page 3 ¶5A 30 days before expiration', null::integer, 3, 54, 449, 10, 10, 'checkbox'),
  ('txr_2001_auto_renewal_notice_other_days_checked', 'Page 3 ¶5A Other notice period selected', null::integer, 3, 54, 462, 10, 10, 'checkbox'),
  ('txr_2001_auto_renewal_notice_other_days', 'Page 3 ¶5A Other days before expiration', null::integer, 3, 89, 460, 91, 16, 'number'),
  ('txr_2001_month_to_month_termination_last_day_next_month', 'Page 3 ¶5B Termination effective last day of following month', null::integer, 3, 54, 568, 10, 10, 'checkbox'),
  ('txr_2001_month_to_month_termination_designated_date', 'Page 3 ¶5B Termination effective designated date', null::integer, 3, 54, 594, 10, 10, 'checkbox'),
  ('txr_2001_unauthorized_animal_initial_charge', 'Page 4 ¶6B Unauthorized animal initial charge', null::integer, 4, 359, 96, 60, 16, 'text'),
  ('txr_2001_unauthorized_animal_daily_charge', 'Page 4 ¶6B Unauthorized animal daily charge', null::integer, 4, 446, 96, 77, 16, 'text'),
  ('txr_2001_utilities_landlord_pays', 'Page 5 ¶8A Utilities paid by Landlord', null::integer, 5, 72, 172, 504, 48, 'text'),
  ('txr_2001_property_is_part_of_hoa', 'Page 5 ¶9B HOA yes', null::integer, 5, 224, 360, 10, 10, 'checkbox'),
  ('txr_2001_property_is_not_part_of_hoa', 'Page 5 ¶9B HOA no', null::integer, 5, 269, 360, 10, 10, 'checkbox'),
  ('txr_2001_hoa_name', 'Page 5 ¶9B HOA name if any', null::integer, 5, 72, 356, 137, 16, 'text'),
  ('txr_2001_guest_consecutive_day_limit', 'Page 5 ¶9D Consecutive guest days', null::integer, 5, 72, 608, 35, 16, 'number'),
  ('txr_2001_vehicle_limit', 'Page 6 ¶10 Max vehicles', null::integer, 6, 324, 56, 36, 16, 'number'),
  ('txr_2001_access_trip_charge', 'Page 6 ¶11C Access trip charge', null::integer, 6, 72, 482, 37, 16, 'text'),
  ('txr_2001_keybox_authorized_last_days', 'Page 6 ¶11D Keybox allowed during last X days', null::integer, 6, 179, 573, 37, 16, 'number'),
  ('txr_2001_keybox_withdrawal_fee', 'Page 6 ¶11D Fee to withdraw keybox authorization', null::integer, 6, 329, 613, 67, 16, 'text'),
  ('txr_2001_move_in_landlord_conditions', 'Page 7 ¶12B Landlord move-in conditions', null::integer, 7, 90, 56, 486, 52, 'text'),
  ('txr_2001_inventory_condition_due_days', 'Page 7 ¶12C Days to deliver inventory/condition form', null::integer, 7, 170, 270, 46, 16, 'number'),
  ('txr_2001_yard_watering_times', 'Page 8 ¶14B Yard watering times', null::integer, 8, 346, 534, 230, 16, 'text'),
  ('txr_2001_yard_maintained_by_landlord', 'Page 8 ¶14B Landlord maintains yard', null::integer, 8, 72, 584, 10, 10, 'checkbox'),
  ('txr_2001_yard_maintained_by_tenant', 'Page 8 ¶14B Tenant maintains yard', null::integer, 8, 72, 623, 10, 10, 'checkbox'),
  ('txr_2001_yard_maintenance_contract_required', 'Page 8 ¶14B Tenant maintains scheduled yard contract', null::integer, 8, 72, 636, 10, 10, 'checkbox'),
  ('txr_2001_yard_maintenance_contract_regular_contractor', 'Page 8 ¶14B Regular contractor', null::integer, 8, 480, 636, 10, 10, 'checkbox'),
  ('txr_2001_yard_maintenance_contract_other_checked', 'Page 8 ¶14B Other contractor selected', null::integer, 8, 265, 648, 10, 10, 'checkbox'),
  ('txr_2001_yard_maintenance_contract_other', 'Page 8 ¶14B Other contractor name/details', null::integer, 8, 278, 646, 293, 16, 'text'),
  ('txr_2001_smoking_permitted', 'Page 9 ¶14F Smoking permitted', null::integer, 9, 138, 388, 10, 10, 'checkbox'),
  ('txr_2001_smoking_not_permitted', 'Page 9 ¶14F Smoking not permitted', null::integer, 9, 201, 388, 10, 10, 'checkbox'),
  ('txr_2001_emergency_repair_phone', 'Page 9 ¶15A Emergency repair phone', null::integer, 9, 181, 561, 137, 16, 'text'),
  ('txr_2001_tenant_specific_repair_items', 'Page 10 ¶15D Specific items/appliances tenant pays to repair', null::integer, 10, 332, 462, 244, 52, 'text'),
  ('txr_2001_special_provisions', 'Page 12 ¶23 Special provisions', null::integer, 12, 72, 285, 504, 72, 'text'),
  ('txr_2001_replacement_tenant_fee_tenant_procures_amount_checked', 'Page 13 ¶25B Tenant procures replacement - flat fee selected', null::integer, 13, 108, 504, 10, 10, 'checkbox'),
  ('txr_2001_replacement_tenant_fee_tenant_procures_amount', 'Page 13 ¶25B Tenant procures replacement flat fee', null::integer, 13, 186, 502, 138, 16, 'text'),
  ('txr_2001_replacement_tenant_fee_tenant_procures_percent_checked', 'Page 13 ¶25B Tenant procures replacement - percent selected', null::integer, 13, 108, 518, 10, 10, 'checkbox'),
  ('txr_2001_replacement_tenant_fee_tenant_procures_percent', 'Page 13 ¶25B Tenant procures replacement percent', null::integer, 13, 180, 516, 54, 16, 'text'),
  ('txr_2001_replacement_tenant_fee_landlord_procures_amount_checked', 'Page 13 ¶25B Landlord procures replacement - flat fee selected', null::integer, 13, 108, 545, 10, 10, 'checkbox'),
  ('txr_2001_replacement_tenant_fee_landlord_procures_amount', 'Page 13 ¶25B Landlord procures replacement flat fee', null::integer, 13, 186, 543, 138, 16, 'text'),
  ('txr_2001_replacement_tenant_fee_landlord_procures_percent_checked', 'Page 13 ¶25B Landlord procures replacement - percent selected', null::integer, 13, 108, 559, 10, 10, 'checkbox'),
  ('txr_2001_replacement_tenant_fee_landlord_procures_percent', 'Page 13 ¶25B Landlord procures replacement percent', null::integer, 13, 180, 557, 54, 16, 'text'),
  ('txr_2001_addendum_rental_flood_disclosure', 'Page 14 ¶28 TXR 2015', null::integer, 14, 54, 107, 10, 10, 'checkbox'),
  ('txr_2001_addendum_agreement_between_brokers', 'Page 14 ¶28 TXR 2002', null::integer, 14, 315, 107, 10, 10, 'checkbox'),
  ('txr_2001_addendum_lead_based_paint', 'Page 14 ¶28 TXR 2008', null::integer, 14, 54, 117, 10, 10, 'checkbox'),
  ('txr_2001_addendum_bed_bug', 'Page 14 ¶28 TXR 2013', null::integer, 14, 315, 117, 10, 10, 'checkbox'),
  ('txr_2001_addendum_inventory_condition_form', 'Page 14 ¶28 TXR 2207', null::integer, 14, 54, 127, 10, 10, 'checkbox'),
  ('txr_2001_addendum_residential_lease_application', 'Page 14 ¶28 TXR 2003', null::integer, 14, 315, 127, 10, 10, 'checkbox'),
  ('txr_2001_addendum_pool_spa', 'Page 14 ¶28 TXR 2010', null::integer, 14, 54, 138, 10, 10, 'checkbox'),
  ('txr_2001_addendum_residential_lease_guaranty', 'Page 14 ¶28 TXR 2007', null::integer, 14, 315, 138, 10, 10, 'checkbox'),
  ('txr_2001_addendum_animal_agreement', 'Page 14 ¶28 TXR 2004', null::integer, 14, 54, 148, 10, 10, 'checkbox'),
  ('txr_2001_addendum_mold_remediation_consumer_protection', 'Page 14 ¶28 TXR 2507', null::integer, 14, 315, 148, 10, 10, 'checkbox'),
  ('txr_2001_addendum_custom_1_checked', 'Page 14 ¶28 Custom addendum', null::integer, 14, 54, 158, 10, 10, 'checkbox'),
  ('txr_2001_addendum_custom_1_text', 'Page 14 ¶28 Custom addendum left', null::integer, 14, 72, 154, 216, 16, 'text'),
  ('txr_2001_addendum_custom_2_checked', 'Page 14 ¶28 Custom addendum', null::integer, 14, 315, 158, 10, 10, 'checkbox'),
  ('txr_2001_addendum_custom_2_text', 'Page 14 ¶28 Custom addendum right', null::integer, 14, 333, 154, 208, 16, 'text'),
  ('txr_2001_addendum_custom_3_checked', 'Page 14 ¶28 Custom addendum', null::integer, 14, 54, 169, 10, 10, 'checkbox'),
  ('txr_2001_addendum_custom_3_text', 'Page 14 ¶28 Custom addendum left', null::integer, 14, 72, 164, 216, 16, 'text'),
  ('txr_2001_addendum_custom_4_checked', 'Page 14 ¶28 Custom addendum', null::integer, 14, 315, 169, 10, 10, 'checkbox'),
  ('txr_2001_addendum_custom_4_text', 'Page 14 ¶28 Custom addendum right', null::integer, 14, 333, 164, 212, 16, 'text'),
  ('txr_2001_tenant_notice_email', 'Page 14 ¶29 Tenant email for notices', null::integer, 14, 85, 258, 221, 16, 'text'),
  ('txr_2001_landlord_notice_email', 'Page 14 ¶29 Landlord email for notices', null::integer, 14, 355, 258, 221, 16, 'text'),
  ('txr_2001_deceased_tenant_contact_name', 'Page 15 ¶31F Non-tenant emergency/death contact', null::integer, 15, 125, 304, 271, 16, 'text'),
  ('txr_2001_deceased_tenant_contact_phone', 'Page 15 ¶31F Contact phone', null::integer, 15, 437, 304, 139, 16, 'text'),
  ('txr_2001_deceased_tenant_contact_address', 'Page 15 ¶31F Contact address', null::integer, 15, 137, 318, 440, 16, 'text'),
  ('txr_2001_deceased_tenant_contact_email', 'Page 15 ¶31F Contact email', null::integer, 15, 127, 331, 449, 16, 'text'),
  ('txr_2001_liability_insurance_required_yes', 'Page 15 ¶31I Landlord requires liability insurance', null::integer, 15, 493, 582, 10, 10, 'checkbox'),
  ('txr_2001_liability_insurance_required_no', 'Page 15 ¶31I Landlord does not require liability insurance', null::integer, 15, 543, 582, 10, 10, 'checkbox'),
  ('txr_2001_liability_insurance_minimum_amount', 'Page 15 ¶31I Minimum liability insurance', null::integer, 15, 419, 531, 106, 16, 'text'),
  ('txr_2001_landlord_broker_name', 'Page 15 ¶31J Landlord broker name', null::integer, 15, 163, 616, 408, 16, 'text'),
  ('txr_2001_landlord_broker_will_manage', 'Page 15 ¶31J Broker will manage', null::integer, 15, 72, 631, 10, 10, 'checkbox'),
  ('txr_2001_landlord_broker_will_not_manage', 'Page 15 ¶31J Broker will not manage', null::integer, 15, 104, 631, 10, 10, 'checkbox'),
  ('txr_2001_managed_by_landlord', 'Page 15 ¶31J Property managed by Landlord', null::integer, 15, 251, 644, 10, 10, 'checkbox'),
  ('txr_2001_managed_by_property_manager', 'Page 15 ¶31J Property managed by Property Manager', null::integer, 15, 320, 644, 10, 10, 'checkbox'),
  ('txr_2001_property_manager_name', 'Page 15 ¶31J Property manager name', null::integer, 15, 211, 665, 257, 16, 'text'),
  ('txr_2001_property_manager_phone', 'Page 15 ¶31J Property manager phone', null::integer, 15, 506, 665, 70, 16, 'text'),
  ('txr_2001_property_manager_address', 'Page 15 ¶31J Property manager address', null::integer, 15, 119, 679, 350, 16, 'text'),
  ('txr_2001_property_manager_email', 'Page 15 ¶31J Property manager email', null::integer, 15, 505, 679, 71, 16, 'text'),
  ('txr_2001_landlord_copy_provided_date', 'Page 16 ¶Landlord Use Landlord copy provided date', null::integer, 16, 51, 282, 237, 16, 'date'),
  ('txr_2001_landlord_copy_provided_to_tenant', 'Page 16 ¶Landlord Use Tenant who received copy', null::integer, 16, 324, 282, 252, 16, 'text'),
  ('txr_2001_copy_delivery_mail', 'Page 16 ¶Landlord Use Copy delivered by mail', null::integer, 16, 276, 483, 10, 10, 'checkbox'),
  ('txr_2001_copy_delivery_email', 'Page 16 ¶Landlord Use Copy delivered by email', null::integer, 16, 312, 483, 10, 10, 'checkbox'),
  ('txr_2001_copy_delivery_in_person', 'Page 16 ¶Landlord Use Copy delivered in person', null::integer, 16, 358, 483, 10, 10, 'checkbox')
;

create temp table txr_2001_mappings_touched (
  field_key text not null,
  page_number integer not null,
  occurrence_index integer,
  action text not null
) on commit drop;

with inserted_mappings as (
  insert into public.form_field_mappings (
    form_id,
    field_id,
    mapping_name,
    occurrence_index,
    page_number,
    x,
    y,
    width,
    height,
    page_width,
    page_height,
    font_size,
    field_widget_type,
    notes,
    status
  )
  select
    tf.form_id,
    fld.id,
    ps.mapping_name,
    ps.occurrence_index,
    ps.page_number,
    ps.x,
    ps.y,
    ps.width,
    ps.height,
    612,
    792,
    9,
    ps.field_widget_type,
    'TXR-2001 Residential Lease first-pass manual/visual placement',
    'ACTIVE'
  from txr_2001_placement_seed ps
  inner join txr_2001_form tf on true
  inner join public.fields fld
    on lower(fld.field_key) = lower(ps.field_key)
   and fld.status = 'ACTIVE'
  where not exists (
    select 1
    from public.form_field_mappings existing
    where existing.form_id = tf.form_id
      and existing.field_id = fld.id
      and existing.page_number = ps.page_number
      and coalesce(existing.occurrence_index, -1) = coalesce(ps.occurrence_index, -1)
      and existing.status = 'ACTIVE'
  )
  returning
    (select field_key from public.fields where id = field_id) as field_key,
    page_number,
    occurrence_index
)
insert into txr_2001_mappings_touched (field_key, page_number, occurrence_index, action)
select field_key, page_number, occurrence_index, 'inserted' from inserted_mappings;

-- ---------------------------------------------------------------------------
-- Report
-- ---------------------------------------------------------------------------

do $$
declare
  v_form_id bigint;
  v_fields_inserted integer;
  v_fields_updated integer;
  v_mappings_inserted integer;
  v_unresolved_fields text;
  v_unresolved_mappings text;
begin
  select form_id into v_form_id from txr_2001_form limit 1;

  select count(*) into v_fields_inserted
  from txr_2001_fields_touched where action = 'inserted';

  select count(*) into v_fields_updated
  from txr_2001_fields_touched where action = 'updated';

  select count(*) into v_mappings_inserted
  from txr_2001_mappings_touched where action = 'inserted';

  raise notice 'TXR-2001 Residential Lease migration report';
  raise notice '  form_id: %', coalesce(v_form_id::text, 'NOT FOUND');
  raise notice '  fields inserted: %', v_fields_inserted;
  raise notice '  fields updated: %', v_fields_updated;
  raise notice '  mappings inserted: %', v_mappings_inserted;

  if v_form_id is null then
    raise notice '  unresolved mappings: form not found; no mappings applied';
  end if;
end $$;
