-- TXR-1102 Residential Lease Listing Agreement field catalog and first-pass PDF mappings.
-- Does not touch public.forms. Schema expansion: 20260630180000_listing_agreement_details_txr_1102_lease_expansion.sql

-- ---------------------------------------------------------------------------
-- Resolve TXR-1102 form
-- ---------------------------------------------------------------------------

create temp table txr_1102_form on commit drop as
select f.id as form_id
from public.forms f
where f.status = 'ACTIVE'
  and (
    lower(trim(f.form_code)) in ('txr-1102', 'txr_1102')
    or lower(trim(f.form_code)) like '%txr-1102%'
    or lower(trim(f.form_code)) like '%txr_1102%'
    or (
      lower(f.form_name) like '%residential%'
      and lower(f.form_name) like '%lease%'
      and lower(f.form_name) like '%listing%'
    )
  )
order by
  case when lower(trim(f.form_code)) in ('txr-1102', 'txr_1102') then 0 else 1 end,
  case
    when lower(f.form_name) like '%txr-1102%' or lower(f.form_name) like '%1102%' then 0
    else 1
  end,
  f.id
limit 1;

-- ---------------------------------------------------------------------------
-- Upsert field definitions (idempotent by field_key)
-- ---------------------------------------------------------------------------

create temp table txr_1102_fields_touched (
  field_key text primary key,
  action text not null
) on commit drop;

with field_seed (
  field_key,
  field_name,
  field_label,
  field_data_type,
  field_widget_type,
  default_value,
  default_checked,
  required,
  notes,
  source_type,
  source_path,
  resolver_key
) as (
  values
    (
      'landlord_name_1',
      'landlord_name_1',
      'Landlord Name 1',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · First active landlord contact name.',
      'packet_contact',
      'landlord_1.full_name',
      null::text
    ),
    (
      'landlord_name_2',
      'landlord_name_2',
      'Landlord Name 2',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Second active landlord contact name.',
      'packet_contact',
      'landlord_2.full_name',
      null::text
    ),
    (
      'landlord_address',
      'landlord_address',
      'Landlord Address',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Primary landlord mailing address.',
      'custom_resolver',
      null::text,
      'landlord_address'
    ),
    (
      'landlord_city_state_zip',
      'landlord_city_state_zip',
      'Landlord City State Zip',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Primary landlord city, state, ZIP.',
      'custom_resolver',
      null::text,
      'landlord_city_state_zip'
    ),
    (
      'landlord_phone',
      'landlord_phone',
      'Landlord Phone',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Primary landlord phone.',
      'packet_contact',
      'landlord_1.phone',
      null::text
    ),
    (
      'landlord_email',
      'landlord_email',
      'Landlord Email',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Primary landlord email.',
      'packet_contact',
      'landlord_1.email',
      null::text
    ),
    (
      'property_lot',
      'property_lot',
      'Property Lot',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'Shared catalog · Property lot from packet property.',
      'packet_property',
      'lot',
      null::text
    ),
    (
      'property_block',
      'property_block',
      'Property Block',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'Shared catalog · Property block from packet property.',
      'packet_property',
      'block',
      null::text
    ),
    (
      'property_addition',
      'property_addition',
      'Property Addition',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'Shared catalog · Property addition/subdivision from packet property.',
      'packet_property',
      'subdivision',
      null::text
    ),
    (
      'property_city',
      'property_city',
      'Property City',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'Shared catalog · Property city from packet property.',
      'packet_property',
      'city',
      null::text
    ),
    (
      'property_county',
      'property_county',
      'Property County',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'Shared catalog · Property county from packet property.',
      'packet_property',
      'county',
      null::text
    ),
    (
      'property_address_zip',
      'property_address_zip',
      'Property ZIP',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'Shared catalog · Property ZIP from packet property.',
      'packet_property',
      'zip',
      null::text
    ),
    (
      'brokerage_name',
      'brokerage_name',
      'Brokerage Name',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'Brokerage/firm name from brokerage_settings.',
      'settings_brokerage',
      'brokerage_name',
      null::text
    ),
    (
      'brokerage_address',
      'brokerage_address',
      'Brokerage Address',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'Brokerage street address from brokerage_settings.',
      'settings_brokerage',
      'brokerage_address',
      null::text
    ),
    (
      'brokerage_city_state_zip',
      'brokerage_city_state_zip',
      'Brokerage City, State, Zip',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'Composite brokerage city, state, and ZIP.',
      'settings_brokerage',
      'brokerage_city_state_zip',
      null::text
    ),
    (
      'brokerage_office_phone',
      'brokerage_office_phone',
      'Brokerage Office Phone',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'Brokerage office phone from brokerage_settings.',
      'settings_brokerage',
      'brokerage_office_phone',
      null::text
    ),
    (
      'brokerage_email',
      'brokerage_email',
      'Brokerage Email',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'Brokerage email from brokerage_settings.',
      'settings_brokerage',
      'brokerage_email',
      null::text
    ),
    (
      'lease_listing_concerning',
      'lease_listing_concerning',
      'Lease Listing Concerning',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Property street address and city for page headers.',
      'custom_resolver',
      null::text,
      'listing_agreement_concerning'
    ),
    (
      'lease_non_real_estate_items',
      'lease_non_real_estate_items',
      'Lease Non Real Estate Items',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Non-real-estate items from listing_agreement_details.',
      'listing_agreement_details',
      'non_real_estate_items',
      null::text
    ),
    (
      'lease_listing_exclusions',
      'lease_listing_exclusions',
      'Lease Listing Exclusions',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Lease listing exclusions from listing_agreement_details.',
      'listing_agreement_details',
      'lease_listing_exclusions',
      null::text
    ),
    (
      'lease_hoa_is_subject',
      'lease_hoa_is_subject',
      'Lease HOA Is Subject',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Property subject to HOA.',
      'listing_agreement_details',
      'hoa_exists',
      null::text
    ),
    (
      'lease_hoa_is_not_subject',
      'lease_hoa_is_not_subject',
      'Lease HOA Is Not Subject',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Inverse of HOA subject.',
      'custom_resolver',
      null::text,
      'listing_hoa_is_not_subject'
    ),
    (
      'lease_monthly_rent',
      'lease_monthly_rent',
      'Lease Monthly Rent',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Monthly rent from listing_agreement_details.',
      'listing_agreement_details',
      'monthly_rent',
      null::text
    ),
    (
      'lease_term_min_months',
      'lease_term_min_months',
      'Lease Term Min Months',
      'integer',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Minimum lease term months.',
      'listing_agreement_details',
      'lease_term_min_months',
      null::text
    ),
    (
      'lease_term_max_months',
      'lease_term_max_months',
      'Lease Term Max Months',
      'integer',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Maximum lease term months.',
      'listing_agreement_details',
      'lease_term_max_months',
      null::text
    ),
    (
      'lease_comp_with_other_broker',
      'lease_comp_with_other_broker',
      'Lease Comp With Other Broker',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Compensation model with other broker.',
      'custom_resolver',
      null::text,
      'lease_compensation_with_other_broker'
    ),
    (
      'lease_broker_fee_one_month_selected',
      'lease_broker_fee_one_month_selected',
      'Lease Broker Fee One Month Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Broker fee one month rent selected.',
      'custom_resolver',
      null::text,
      'lease_broker_fee_one_month_selected'
    ),
    (
      'lease_broker_fee_one_month_percent',
      'lease_broker_fee_one_month_percent',
      'Lease Broker Fee One Month Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Broker fee one month rent percent.',
      'listing_agreement_details',
      'broker_fee_one_month_percent',
      null::text
    ),
    (
      'lease_broker_fee_all_rents_selected',
      'lease_broker_fee_all_rents_selected',
      'Lease Broker Fee All Rents Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Broker fee all rents selected.',
      'custom_resolver',
      null::text,
      'lease_broker_fee_all_rents_selected'
    ),
    (
      'lease_broker_fee_all_rents_percent',
      'lease_broker_fee_all_rents_percent',
      'Lease Broker Fee All Rents Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Broker fee all rents percent.',
      'listing_agreement_details',
      'broker_fee_all_rents_percent',
      null::text
    ),
    (
      'lease_broker_fee_other_selected',
      'lease_broker_fee_other_selected',
      'Lease Broker Fee Other Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Broker fee other selected.',
      'custom_resolver',
      null::text,
      'lease_broker_fee_other_selected'
    ),
    (
      'lease_broker_fee_other',
      'lease_broker_fee_other',
      'Lease Broker Fee Other',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Other broker fee description.',
      'listing_agreement_details',
      'broker_fee_other',
      null::text
    ),
    (
      'lease_other_broker_one_month_selected',
      'lease_other_broker_one_month_selected',
      'Lease Other Broker One Month Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Other broker one month selected.',
      'custom_resolver',
      null::text,
      'lease_other_broker_one_month_selected'
    ),
    (
      'lease_other_broker_one_month_percent',
      'lease_other_broker_one_month_percent',
      'Lease Other Broker One Month Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Other broker one month percent.',
      'listing_agreement_details',
      'other_broker_one_month_percent',
      null::text
    ),
    (
      'lease_other_broker_all_rents_selected',
      'lease_other_broker_all_rents_selected',
      'Lease Other Broker All Rents Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Other broker all rents selected.',
      'custom_resolver',
      null::text,
      'lease_other_broker_all_rents_selected'
    ),
    (
      'lease_other_broker_all_rents_percent',
      'lease_other_broker_all_rents_percent',
      'Lease Other Broker All Rents Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Other broker all rents percent.',
      'listing_agreement_details',
      'other_broker_all_rents_percent',
      null::text
    ),
    (
      'lease_other_broker_flat_fee_selected',
      'lease_other_broker_flat_fee_selected',
      'Lease Other Broker Flat Fee Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Other broker flat fee selected.',
      'custom_resolver',
      null::text,
      'lease_other_broker_flat_fee_selected'
    ),
    (
      'lease_other_broker_flat_fee',
      'lease_other_broker_flat_fee',
      'Lease Other Broker Flat Fee',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Other broker flat fee amount.',
      'listing_agreement_details',
      'other_broker_flat_fee',
      null::text
    ),
    (
      'lease_comp_without_other_broker',
      'lease_comp_without_other_broker',
      'Lease Comp Without Other Broker',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Compensation without other broker.',
      'custom_resolver',
      null::text,
      'lease_compensation_without_other_broker'
    ),
    (
      'lease_no_coop_one_month_selected',
      'lease_no_coop_one_month_selected',
      'Lease No Coop One Month Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · No co-op one month selected.',
      'custom_resolver',
      null::text,
      'lease_no_coop_one_month_selected'
    ),
    (
      'lease_no_coop_one_month_percent',
      'lease_no_coop_one_month_percent',
      'Lease No Coop One Month Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · No co-op one month percent (5B).',
      'listing_agreement_details',
      'broker_fee_one_month_percent',
      null::text
    ),
    (
      'lease_no_coop_all_rents_selected',
      'lease_no_coop_all_rents_selected',
      'Lease No Coop All Rents Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · No co-op all rents selected.',
      'custom_resolver',
      null::text,
      'lease_no_coop_all_rents_selected'
    ),
    (
      'lease_no_coop_all_rents_percent',
      'lease_no_coop_all_rents_percent',
      'Lease No Coop All Rents Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · No co-op all rents percent (5B).',
      'listing_agreement_details',
      'broker_fee_all_rents_percent',
      null::text
    ),
    (
      'lease_no_coop_other_selected',
      'lease_no_coop_other_selected',
      'Lease No Coop Other Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · No co-op other selected.',
      'custom_resolver',
      null::text,
      'lease_no_coop_other_selected'
    ),
    (
      'lease_no_coop_other',
      'lease_no_coop_other',
      'Lease No Coop Other',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · No co-op other compensation (5B).',
      'listing_agreement_details',
      'broker_fee_other',
      null::text
    ),
    (
      'lease_renewal_one_month_selected',
      'lease_renewal_one_month_selected',
      'Lease Renewal One Month Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Renewal one month selected.',
      'custom_resolver',
      null::text,
      'lease_renewal_one_month_selected'
    ),
    (
      'lease_renewal_one_month_percent',
      'lease_renewal_one_month_percent',
      'Lease Renewal One Month Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Renewal one month percent.',
      'listing_agreement_details',
      'renewal_one_month_percent',
      null::text
    ),
    (
      'lease_renewal_all_rents_selected',
      'lease_renewal_all_rents_selected',
      'Lease Renewal All Rents Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Renewal all rents selected.',
      'custom_resolver',
      null::text,
      'lease_renewal_all_rents_selected'
    ),
    (
      'lease_renewal_all_rents_percent',
      'lease_renewal_all_rents_percent',
      'Lease Renewal All Rents Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Renewal all rents percent.',
      'listing_agreement_details',
      'renewal_all_rents_percent',
      null::text
    ),
    (
      'lease_renewal_other_selected',
      'lease_renewal_other_selected',
      'Lease Renewal Other Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Renewal other selected.',
      'custom_resolver',
      null::text,
      'lease_renewal_other_selected'
    ),
    (
      'lease_renewal_other',
      'lease_renewal_other',
      'Lease Renewal Other',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Renewal other compensation.',
      'listing_agreement_details',
      'renewal_other',
      null::text
    ),
    (
      'lease_sale_comp_percent_selected',
      'lease_sale_comp_percent_selected',
      'Lease Sale Comp Percent Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Sale compensation percent selected.',
      'custom_resolver',
      null::text,
      'lease_sale_comp_percent_selected'
    ),
    (
      'lease_sale_comp_percent',
      'lease_sale_comp_percent',
      'Lease Sale Comp Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Sale compensation percent.',
      'listing_agreement_details',
      'sale_compensation_percent',
      null::text
    ),
    (
      'lease_sale_comp_other_selected',
      'lease_sale_comp_other_selected',
      'Lease Sale Comp Other Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Sale compensation other selected.',
      'custom_resolver',
      null::text,
      'lease_sale_comp_other_selected'
    ),
    (
      'lease_sale_comp_other',
      'lease_sale_comp_other',
      'Lease Sale Comp Other',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Sale compensation other.',
      'listing_agreement_details',
      'sale_compensation_other',
      null::text
    ),
    (
      'lease_reimbursable_expenses',
      'lease_reimbursable_expenses',
      'Lease Reimbursable Expenses',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Reimbursable expenses.',
      'listing_agreement_details',
      'reimbursable_expenses',
      null::text
    ),
    (
      'lease_protection_period_days',
      'lease_protection_period_days',
      'Lease Protection Period Days',
      'integer',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Protection period days.',
      'listing_agreement_details',
      'lease_protection_period_days',
      null::text
    ),
    (
      'lease_payment_county',
      'lease_payment_county',
      'Lease Payment County',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Payment county.',
      'listing_agreement_details',
      'lease_payment_county',
      null::text
    ),
    (
      'lease_mls_file_listing',
      'lease_mls_file_listing',
      'Lease MLS File Listing',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · MLS filing authorized.',
      'custom_resolver',
      null::text,
      'lease_mls_file_listing'
    ),
    (
      'lease_mls_file_immediately',
      'lease_mls_file_immediately',
      'Lease MLS File Immediately',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · File in MLS immediately.',
      'custom_resolver',
      null::text,
      'lease_mls_file_immediately'
    ),
    (
      'lease_mls_delay_filing',
      'lease_mls_delay_filing',
      'Lease MLS Delay Filing',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Delayed MLS filing.',
      'custom_resolver',
      null::text,
      'lease_mls_delay_filing'
    ),
    (
      'lease_mls_delayed_days',
      'lease_mls_delayed_days',
      'Lease MLS Delayed Days',
      'integer',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · MLS delayed days.',
      'listing_agreement_details',
      'lease_mls_delayed_days',
      null::text
    ),
    (
      'lease_mls_delayed_purpose',
      'lease_mls_delayed_purpose',
      'Lease MLS Delayed Purpose',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · MLS delayed purpose.',
      'listing_agreement_details',
      'lease_mls_delayed_purpose',
      null::text
    ),
    (
      'lease_mls_no_filing',
      'lease_mls_no_filing',
      'Lease MLS No Filing',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · No MLS filing.',
      'custom_resolver',
      null::text,
      'lease_mls_no_filing'
    ),
    (
      'lease_scheduling_company',
      'lease_scheduling_company',
      'Lease Scheduling Company',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Scheduling company.',
      'listing_agreement_details',
      'lease_scheduling_company',
      null::text
    ),
    (
      'lease_keybox_authorized_yes',
      'lease_keybox_authorized_yes',
      'Lease Keybox Authorized Yes',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Keybox authorized.',
      'listing_agreement_details',
      'lease_keybox_authorized',
      null::text
    ),
    (
      'lease_keybox_authorized_no',
      'lease_keybox_authorized_no',
      'Lease Keybox Authorized No',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Keybox not authorized.',
      'custom_resolver',
      null::text,
      'lease_keybox_authorized_no'
    ),
    (
      'lease_intermediary_yes',
      'lease_intermediary_yes',
      'Lease Intermediary Yes',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Intermediary allowed (manual).',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'lease_intermediary_no',
      'lease_intermediary_no',
      'Lease Intermediary No',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Intermediary not allowed (manual).',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'lease_internet_no_display',
      'lease_internet_no_display',
      'Lease Internet No Display',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · No internet display.',
      'custom_resolver',
      null::text,
      'lease_internet_no_display'
    ),
    (
      'lease_internet_no_address_display',
      'lease_internet_no_address_display',
      'Lease Internet No Address Display',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · No address internet display.',
      'custom_resolver',
      null::text,
      'lease_internet_no_address_display'
    ),
    (
      'lease_make_ready_not_authorized',
      'lease_make_ready_not_authorized',
      'Lease Make Ready Not Authorized',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Broker not authorized for make ready.',
      'custom_resolver',
      null::text,
      'lease_make_ready_not_authorized'
    ),
    (
      'lease_make_ready_authorized',
      'lease_make_ready_authorized',
      'Lease Make Ready Authorized',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Broker authorized for make ready.',
      'custom_resolver',
      null::text,
      'lease_make_ready_authorized'
    ),
    (
      'lease_make_ready_cost_cap',
      'lease_make_ready_cost_cap',
      'Lease Make Ready Cost Cap',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Make ready cost cap.',
      'listing_agreement_details',
      'make_ready_cost_cap',
      null::text
    ),
    (
      'lease_make_ready_landlord_pays_contractors',
      'lease_make_ready_landlord_pays_contractors',
      'Lease Make Ready Landlord Pays Contractors',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Landlord pays contractors.',
      'listing_agreement_details',
      'make_ready_landlord_pays_contractors',
      null::text
    ),
    (
      'lease_make_ready_direct_service_fee',
      'lease_make_ready_direct_service_fee',
      'Lease Make Ready Direct Service Fee',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Make ready direct service fee.',
      'listing_agreement_details',
      'make_ready_service_fee',
      null::text
    ),
    (
      'lease_make_ready_broker_reimbursed',
      'lease_make_ready_broker_reimbursed',
      'Lease Make Ready Broker Reimbursed',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Broker reimbursed for make ready.',
      'listing_agreement_details',
      'make_ready_broker_reimbursed',
      null::text
    ),
    (
      'lease_make_ready_reimbursement_service_fee',
      'lease_make_ready_reimbursement_service_fee',
      'Lease Make Ready Reimbursement Service Fee',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Make ready reimbursement service fee.',
      'listing_agreement_details',
      'make_ready_service_fee',
      null::text
    ),
    (
      'lease_known_financial_obligations_exception',
      'lease_known_financial_obligations_exception',
      'Lease Known Financial Obligations Exception',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Known financial obligations exception.',
      'listing_agreement_details',
      'lease_known_financial_obligations_exception',
      null::text
    ),
    (
      'lease_known_liens_exception',
      'lease_known_liens_exception',
      'Lease Known Liens Exception',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Known liens exception.',
      'listing_agreement_details',
      'lease_known_liens_exception',
      null::text
    ),
    (
      'lease_optional_common_area_fees_exception',
      'lease_optional_common_area_fees_exception',
      'Lease Optional Common Area Fees Exception',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Optional common area fees exception.',
      'listing_agreement_details',
      'optional_common_area_fees_exception',
      null::text
    ),
    (
      'lease_health_safety_condition_exception',
      'lease_health_safety_condition_exception',
      'Lease Health Safety Condition Exception',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Health/safety condition exception.',
      'listing_agreement_details',
      'health_safety_condition_exception',
      null::text
    ),
    (
      'lease_special_provisions',
      'lease_special_provisions',
      'Lease Special Provisions',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Special provisions.',
      'listing_agreement_details',
      'lease_special_provisions',
      null::text
    ),
    (
      'lease_add_iabs',
      'lease_add_iabs',
      'Lease Add IABS',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Include IABS addendum.',
      'listing_agreement_details',
      'lease_add_iabs',
      null::text
    ),
    (
      'lease_add_rental_flood_disclosure',
      'lease_add_rental_flood_disclosure',
      'Lease Add Rental Flood Disclosure',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Include rental flood disclosure.',
      'listing_agreement_details',
      'lease_add_rental_flood_disclosure',
      null::text
    ),
    (
      'lease_add_lead_paint',
      'lease_add_lead_paint',
      'Lease Add Lead Paint',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Include lead paint addendum.',
      'listing_agreement_details',
      'lease_add_lead_paint',
      null::text
    ),
    (
      'lease_add_hoa_request',
      'lease_add_hoa_request',
      'Lease Add HOA Request',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Include HOA request.',
      'listing_agreement_details',
      'lease_add_hoa_request',
      null::text
    ),
    (
      'lease_add_flood_hazard',
      'lease_add_flood_hazard',
      'Lease Add Flood Hazard',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Include flood hazard addendum.',
      'listing_agreement_details',
      'lease_add_flood_hazard',
      null::text
    ),
    (
      'lease_add_condo_addendum',
      'lease_add_condo_addendum',
      'Lease Add Condo Addendum',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Include condo addendum.',
      'listing_agreement_details',
      'lease_add_condo_addendum',
      null::text
    ),
    (
      'lease_add_keybox_tenant',
      'lease_add_keybox_tenant',
      'Lease Add Keybox Tenant',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Include keybox tenant addendum.',
      'listing_agreement_details',
      'lease_add_keybox_tenant',
      null::text
    ),
    (
      'lease_add_onsite_sewer',
      'lease_add_onsite_sewer',
      'Lease Add Onsite Sewer',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Include onsite sewer addendum.',
      'listing_agreement_details',
      'lease_add_onsite_sewer',
      null::text
    ),
    (
      'lease_add_irs_forms',
      'lease_add_irs_forms',
      'Lease Add IRS Forms',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Include IRS forms addendum.',
      'listing_agreement_details',
      'lease_add_irs_forms',
      null::text
    ),
    (
      'lease_add_unescorted_access',
      'lease_add_unescorted_access',
      'Lease Add Unescorted Access',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Include unescorted access addendum.',
      'listing_agreement_details',
      'lease_add_unescorted_access',
      null::text
    ),
    (
      'lease_add_assistance_animals',
      'lease_add_assistance_animals',
      'Lease Add Assistance Animals',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Include assistance animals addendum.',
      'listing_agreement_details',
      'lease_add_assistance_animals',
      null::text
    ),
    (
      'lease_add_other_document',
      'lease_add_other_document',
      'Lease Add Other Document',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Include other document addendum.',
      'listing_agreement_details',
      'lease_add_other_document',
      null::text
    ),
    (
      'lease_add_other_document_description',
      'lease_add_other_document_description',
      'Lease Add Other Document Description',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Other document description.',
      'listing_agreement_details',
      'lease_add_other_document_description',
      null::text
    ),
    (
      'lease_rent_due_first_day',
      'lease_rent_due_first_day',
      'Lease Rent Due First Day',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Rent due on first day.',
      'listing_agreement_details',
      'rent_due_first_day',
      null::text
    ),
    (
      'lease_rent_due_other_selected',
      'lease_rent_due_other_selected',
      'Lease Rent Due Other Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Rent due other day selected.',
      'custom_resolver',
      null::text,
      'lease_rent_due_other_selected'
    ),
    (
      'lease_rent_due_other',
      'lease_rent_due_other',
      'Lease Rent Due Other',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Other rent due day.',
      'listing_agreement_details',
      'rent_due_other',
      null::text
    ),
    (
      'lease_initial_late_charge_amount_selected',
      'lease_initial_late_charge_amount_selected',
      'Lease Initial Late Charge Amount Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Initial late charge amount selected.',
      'custom_resolver',
      null::text,
      'lease_initial_late_charge_amount_selected'
    ),
    (
      'lease_initial_late_charge_amount',
      'lease_initial_late_charge_amount',
      'Lease Initial Late Charge Amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Initial late charge amount.',
      'listing_agreement_details',
      'initial_late_charge_amount',
      null::text
    ),
    (
      'lease_initial_late_charge_percent_selected',
      'lease_initial_late_charge_percent_selected',
      'Lease Initial Late Charge Percent Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Initial late charge percent selected.',
      'custom_resolver',
      null::text,
      'lease_initial_late_charge_percent_selected'
    ),
    (
      'lease_initial_late_charge_percent',
      'lease_initial_late_charge_percent',
      'Lease Initial Late Charge Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Initial late charge percent.',
      'listing_agreement_details',
      'initial_late_charge_percent',
      null::text
    ),
    (
      'lease_additional_late_charge_daily_amount',
      'lease_additional_late_charge_daily_amount',
      'Lease Additional Late Charge Daily Amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Additional daily late charge.',
      'listing_agreement_details',
      'additional_late_charge_daily_amount',
      null::text
    ),
    (
      'lease_animals_not_permitted',
      'lease_animals_not_permitted',
      'Lease Animals Not Permitted',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Animals not permitted.',
      'listing_agreement_details',
      'animals_not_permitted',
      null::text
    ),
    (
      'lease_animals_permitted',
      'lease_animals_permitted',
      'Lease Animals Permitted',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Animals permitted.',
      'listing_agreement_details',
      'animals_permitted',
      null::text
    ),
    (
      'lease_animal_restrictions',
      'lease_animal_restrictions',
      'Lease Animal Restrictions',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Animal restrictions.',
      'listing_agreement_details',
      'animal_restrictions',
      null::text
    ),
    (
      'lease_animal_deposit',
      'lease_animal_deposit',
      'Lease Animal Deposit',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Animal deposit.',
      'listing_agreement_details',
      'animal_deposit',
      null::text
    ),
    (
      'lease_animal_monthly_rent_increase',
      'lease_animal_monthly_rent_increase',
      'Lease Animal Monthly Rent Increase',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Animal monthly rent increase.',
      'listing_agreement_details',
      'animal_monthly_rent_increase',
      null::text
    ),
    (
      'lease_animal_nonrefundable_fee',
      'lease_animal_nonrefundable_fee',
      'Lease Animal Nonrefundable Fee',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Animal nonrefundable fee.',
      'listing_agreement_details',
      'animal_nonrefundable_fee',
      null::text
    ),
    (
      'lease_animal_violation_initial_charge',
      'lease_animal_violation_initial_charge',
      'Lease Animal Violation Initial Charge',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Animal violation initial charge.',
      'listing_agreement_details',
      'animal_violation_initial_charge',
      null::text
    ),
    (
      'lease_animal_violation_daily_charge',
      'lease_animal_violation_daily_charge',
      'Lease Animal Violation Daily Charge',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Animal violation daily charge.',
      'listing_agreement_details',
      'animal_violation_daily_charge',
      null::text
    ),
    (
      'lease_security_deposit',
      'lease_security_deposit',
      'Lease Security Deposit',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Security deposit.',
      'listing_agreement_details',
      'security_deposit',
      null::text
    ),
    (
      'lease_tenant_utilities_except',
      'lease_tenant_utilities_except',
      'Lease Tenant Utilities Except',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Tenant utilities except.',
      'listing_agreement_details',
      'tenant_utilities_except',
      null::text
    ),
    (
      'lease_guest_days',
      'lease_guest_days',
      'Lease Guest Days',
      'integer',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Guest days.',
      'listing_agreement_details',
      'guest_days',
      null::text
    ),
    (
      'lease_vehicle_count',
      'lease_vehicle_count',
      'Lease Vehicle Count',
      'integer',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Vehicle count.',
      'listing_agreement_details',
      'vehicle_count',
      null::text
    ),
    (
      'lease_trip_charge',
      'lease_trip_charge',
      'Lease Trip Charge',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Trip charge.',
      'listing_agreement_details',
      'trip_charge',
      null::text
    ),
    (
      'lease_keybox_last_days',
      'lease_keybox_last_days',
      'Lease Keybox Last Days',
      'integer',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Keybox last days.',
      'listing_agreement_details',
      'keybox_last_days',
      null::text
    ),
    (
      'lease_early_withdrawal_fee',
      'lease_early_withdrawal_fee',
      'Lease Early Withdrawal Fee',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Early withdrawal fee.',
      'listing_agreement_details',
      'early_withdrawal_fee',
      null::text
    ),
    (
      'lease_inventory_condition_form_days',
      'lease_inventory_condition_form_days',
      'Lease Inventory Condition Form Days',
      'integer',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Inventory condition form days.',
      'listing_agreement_details',
      'inventory_condition_form_days',
      null::text
    ),
    (
      'lease_yard_landlord',
      'lease_yard_landlord',
      'Lease Yard Landlord',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Yard maintained by landlord.',
      'custom_resolver',
      null::text,
      'lease_yard_maintained_by_landlord'
    ),
    (
      'lease_yard_tenant',
      'lease_yard_tenant',
      'Lease Yard Tenant',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Yard maintained by tenant.',
      'custom_resolver',
      null::text,
      'lease_yard_maintained_by_tenant'
    ),
    (
      'lease_yard_contractor_tenant_paid',
      'lease_yard_contractor_tenant_paid',
      'Lease Yard Contractor Tenant Paid',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Yard maintained by contractor paid by tenant.',
      'custom_resolver',
      null::text,
      'lease_yard_maintained_by_contractor'
    ),
    (
      'lease_yard_contractor_name',
      'lease_yard_contractor_name',
      'Lease Yard Contractor Name',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Yard contractor name (manual).',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'lease_pool_landlord',
      'lease_pool_landlord',
      'Lease Pool Landlord',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Pool/spa maintained by landlord.',
      'custom_resolver',
      null::text,
      'lease_pool_maintained_by_landlord'
    ),
    (
      'lease_pool_tenant',
      'lease_pool_tenant',
      'Lease Pool Tenant',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Pool/spa maintained by tenant.',
      'custom_resolver',
      null::text,
      'lease_pool_maintained_by_tenant'
    ),
    (
      'lease_pool_contractor_tenant_paid',
      'lease_pool_contractor_tenant_paid',
      'Lease Pool Contractor Tenant Paid',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Pool/spa maintained by contractor paid by tenant.',
      'custom_resolver',
      null::text,
      'lease_pool_maintained_by_contractor'
    ),
    (
      'lease_pool_contractor_name',
      'lease_pool_contractor_name',
      'Lease Pool Contractor Name',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Pool/spa contractor name (manual).',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'lease_pool_other',
      'lease_pool_other',
      'Lease Pool Other',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Pool/spa other maintenance option.',
      'custom_resolver',
      null::text,
      'lease_pool_maintained_by_other'
    ),
    (
      'lease_pool_other_text',
      'lease_pool_other_text',
      'Lease Pool Other Text',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Pool/spa other maintenance text (manual).',
      'manual_only',
      null::text,
      null::text
    ),
    (
      'lease_emergency_repair_phone',
      'lease_emergency_repair_phone',
      'Lease Emergency Repair Phone',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Emergency repair phone.',
      'listing_agreement_details',
      'emergency_repair_phone',
      null::text
    ),
    (
      'lease_items_not_repaired',
      'lease_items_not_repaired',
      'Lease Items Not Repaired',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Items not repaired.',
      'listing_agreement_details',
      'items_not_repaired',
      null::text
    ),
    (
      'lease_tenant_liability_insurance_amount',
      'lease_tenant_liability_insurance_amount',
      'Lease Tenant Liability Insurance Amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Tenant liability insurance amount.',
      'listing_agreement_details',
      'tenant_liability_insurance_amount',
      null::text
    ),
    (
      'lease_replacement_tenant_by_tenant_amount_selected',
      'lease_replacement_tenant_by_tenant_amount_selected',
      'Lease Replacement Tenant By Tenant Amount Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Replacement tenant by tenant amount selected.',
      'custom_resolver',
      null::text,
      'lease_replacement_tenant_by_tenant_amount_selected'
    ),
    (
      'lease_replacement_tenant_by_tenant_amount',
      'lease_replacement_tenant_by_tenant_amount',
      'Lease Replacement Tenant By Tenant Amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Replacement tenant by tenant amount.',
      'listing_agreement_details',
      'replacement_tenant_by_tenant_amount',
      null::text
    ),
    (
      'lease_replacement_tenant_by_tenant_percent_selected',
      'lease_replacement_tenant_by_tenant_percent_selected',
      'Lease Replacement Tenant By Tenant Percent Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Replacement tenant by tenant percent selected.',
      'custom_resolver',
      null::text,
      'lease_replacement_tenant_by_tenant_percent_selected'
    ),
    (
      'lease_replacement_tenant_by_tenant_percent',
      'lease_replacement_tenant_by_tenant_percent',
      'Lease Replacement Tenant By Tenant Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Replacement tenant by tenant percent.',
      'listing_agreement_details',
      'replacement_tenant_by_tenant_percent',
      null::text
    ),
    (
      'lease_replacement_tenant_by_landlord_amount_selected',
      'lease_replacement_tenant_by_landlord_amount_selected',
      'Lease Replacement Tenant By Landlord Amount Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Replacement tenant by landlord amount selected.',
      'custom_resolver',
      null::text,
      'lease_replacement_tenant_by_landlord_amount_selected'
    ),
    (
      'lease_replacement_tenant_by_landlord_amount',
      'lease_replacement_tenant_by_landlord_amount',
      'Lease Replacement Tenant By Landlord Amount',
      'currency',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Replacement tenant by landlord amount.',
      'listing_agreement_details',
      'replacement_tenant_by_landlord_amount',
      null::text
    ),
    (
      'lease_replacement_tenant_by_landlord_percent_selected',
      'lease_replacement_tenant_by_landlord_percent_selected',
      'Lease Replacement Tenant By Landlord Percent Selected',
      'boolean',
      'checkbox',
      null::text,
      false,
      false,
      'TXR-1102 · Replacement tenant by landlord percent selected.',
      'custom_resolver',
      null::text,
      'lease_replacement_tenant_by_landlord_percent_selected'
    ),
    (
      'lease_replacement_tenant_by_landlord_percent',
      'lease_replacement_tenant_by_landlord_percent',
      'Lease Replacement Tenant By Landlord Percent',
      'number',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Replacement tenant by landlord percent.',
      'listing_agreement_details',
      'replacement_tenant_by_landlord_percent',
      null::text
    ),
    (
      'lease_requirements_special_provisions',
      'lease_requirements_special_provisions',
      'Lease Requirements Special Provisions',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Lease requirements special provisions.',
      'listing_agreement_details',
      'lease_requirements_special_provisions',
      null::text
    ),
    (
      'lease_requirements_other',
      'lease_requirements_other',
      'Lease Requirements Other',
      'text',
      'text',
      null::text,
      null::boolean,
      false,
      'TXR-1102 · Lease requirements other.',
      'listing_agreement_details',
      'lease_requirements_other',
      null::text
    )
),
inserted_fields as (
  insert into public.fields (
    field_key,
    field_name,
    field_label,
    field_data_type,
    field_widget_type,
    default_value,
    default_checked,
    required,
    notes,
    source_type,
    source_path,
    resolver_key,
    status
  )
  select
    s.field_key,
    s.field_name,
    s.field_label,
    s.field_data_type,
    s.field_widget_type,
    s.default_value,
    s.default_checked,
    s.required,
    s.notes,
    s.source_type,
    s.source_path,
    s.resolver_key,
    'ACTIVE'
  from field_seed s
  where not exists (
    select 1
    from public.fields existing
    where lower(existing.field_key) = lower(s.field_key)
      and existing.status = 'ACTIVE'
  )
  returning field_key
),
updated_fields as (
  update public.fields target
  set
    field_name = s.field_name,
    field_label = s.field_label,
    field_data_type = s.field_data_type,
    field_widget_type = s.field_widget_type,
    default_value = s.default_value,
    default_checked = s.default_checked,
    required = s.required,
    notes = s.notes,
    source_type = s.source_type,
    source_path = s.source_path,
    resolver_key = s.resolver_key,
    update_date = now()
  from field_seed s
  where lower(target.field_key) = lower(s.field_key)
    and target.status = 'ACTIVE'
  returning target.field_key
)
insert into txr_1102_fields_touched (field_key, action)
select field_key, 'inserted' from inserted_fields
union all
select field_key, 'updated' from updated_fields;

-- ---------------------------------------------------------------------------
-- Deactivate existing ACTIVE mappings for seeded field keys (TXR-1102 only)
-- ---------------------------------------------------------------------------

with mapping_field_keys(field_key) as (
  values
    ('brokerage_address'),
    ('brokerage_city_state_zip'),
    ('brokerage_email'),
    ('brokerage_name'),
    ('brokerage_office_phone'),
    ('landlord_address'),
    ('landlord_city_state_zip'),
    ('landlord_email'),
    ('landlord_name_1'),
    ('landlord_name_2'),
    ('landlord_phone'),
    ('lease_add_assistance_animals'),
    ('lease_add_condo_addendum'),
    ('lease_add_flood_hazard'),
    ('lease_add_hoa_request'),
    ('lease_add_iabs'),
    ('lease_add_irs_forms'),
    ('lease_add_keybox_tenant'),
    ('lease_add_lead_paint'),
    ('lease_add_onsite_sewer'),
    ('lease_add_other_document'),
    ('lease_add_other_document_description'),
    ('lease_add_rental_flood_disclosure'),
    ('lease_add_unescorted_access'),
    ('lease_additional_late_charge_daily_amount'),
    ('lease_animal_deposit'),
    ('lease_animal_monthly_rent_increase'),
    ('lease_animal_nonrefundable_fee'),
    ('lease_animal_restrictions'),
    ('lease_animal_violation_daily_charge'),
    ('lease_animal_violation_initial_charge'),
    ('lease_animals_not_permitted'),
    ('lease_animals_permitted'),
    ('lease_broker_fee_all_rents_percent'),
    ('lease_broker_fee_all_rents_selected'),
    ('lease_broker_fee_one_month_percent'),
    ('lease_broker_fee_one_month_selected'),
    ('lease_broker_fee_other'),
    ('lease_broker_fee_other_selected'),
    ('lease_comp_with_other_broker'),
    ('lease_comp_without_other_broker'),
    ('lease_early_withdrawal_fee'),
    ('lease_emergency_repair_phone'),
    ('lease_guest_days'),
    ('lease_health_safety_condition_exception'),
    ('lease_hoa_is_not_subject'),
    ('lease_hoa_is_subject'),
    ('lease_initial_late_charge_amount'),
    ('lease_initial_late_charge_amount_selected'),
    ('lease_initial_late_charge_percent'),
    ('lease_initial_late_charge_percent_selected'),
    ('lease_intermediary_no'),
    ('lease_intermediary_yes'),
    ('lease_internet_no_address_display'),
    ('lease_internet_no_display'),
    ('lease_inventory_condition_form_days'),
    ('lease_items_not_repaired'),
    ('lease_keybox_authorized_no'),
    ('lease_keybox_authorized_yes'),
    ('lease_keybox_last_days'),
    ('lease_known_financial_obligations_exception'),
    ('lease_known_liens_exception'),
    ('lease_listing_concerning'),
    ('lease_listing_exclusions'),
    ('lease_make_ready_authorized'),
    ('lease_make_ready_broker_reimbursed'),
    ('lease_make_ready_cost_cap'),
    ('lease_make_ready_direct_service_fee'),
    ('lease_make_ready_landlord_pays_contractors'),
    ('lease_make_ready_not_authorized'),
    ('lease_make_ready_reimbursement_service_fee'),
    ('lease_mls_delay_filing'),
    ('lease_mls_delayed_days'),
    ('lease_mls_delayed_purpose'),
    ('lease_mls_file_immediately'),
    ('lease_mls_file_listing'),
    ('lease_mls_no_filing'),
    ('lease_monthly_rent'),
    ('lease_no_coop_all_rents_percent'),
    ('lease_no_coop_all_rents_selected'),
    ('lease_no_coop_one_month_percent'),
    ('lease_no_coop_one_month_selected'),
    ('lease_no_coop_other'),
    ('lease_no_coop_other_selected'),
    ('lease_non_real_estate_items'),
    ('lease_optional_common_area_fees_exception'),
    ('lease_other_broker_all_rents_percent'),
    ('lease_other_broker_all_rents_selected'),
    ('lease_other_broker_flat_fee'),
    ('lease_other_broker_flat_fee_selected'),
    ('lease_other_broker_one_month_percent'),
    ('lease_other_broker_one_month_selected'),
    ('lease_payment_county'),
    ('lease_pool_contractor_name'),
    ('lease_pool_contractor_tenant_paid'),
    ('lease_pool_landlord'),
    ('lease_pool_other'),
    ('lease_pool_other_text'),
    ('lease_pool_tenant'),
    ('lease_protection_period_days'),
    ('lease_reimbursable_expenses'),
    ('lease_renewal_all_rents_percent'),
    ('lease_renewal_all_rents_selected'),
    ('lease_renewal_one_month_percent'),
    ('lease_renewal_one_month_selected'),
    ('lease_renewal_other'),
    ('lease_renewal_other_selected'),
    ('lease_rent_due_first_day'),
    ('lease_rent_due_other'),
    ('lease_rent_due_other_selected'),
    ('lease_replacement_tenant_by_landlord_amount'),
    ('lease_replacement_tenant_by_landlord_amount_selected'),
    ('lease_replacement_tenant_by_landlord_percent'),
    ('lease_replacement_tenant_by_landlord_percent_selected'),
    ('lease_replacement_tenant_by_tenant_amount'),
    ('lease_replacement_tenant_by_tenant_amount_selected'),
    ('lease_replacement_tenant_by_tenant_percent'),
    ('lease_replacement_tenant_by_tenant_percent_selected'),
    ('lease_requirements_other'),
    ('lease_requirements_special_provisions'),
    ('lease_sale_comp_other'),
    ('lease_sale_comp_other_selected'),
    ('lease_sale_comp_percent'),
    ('lease_sale_comp_percent_selected'),
    ('lease_scheduling_company'),
    ('lease_security_deposit'),
    ('lease_special_provisions'),
    ('lease_tenant_liability_insurance_amount'),
    ('lease_tenant_utilities_except'),
    ('lease_term_max_months'),
    ('lease_term_min_months'),
    ('lease_trip_charge'),
    ('lease_vehicle_count'),
    ('lease_yard_contractor_name'),
    ('lease_yard_contractor_tenant_paid'),
    ('lease_yard_landlord'),
    ('lease_yard_tenant'),
    ('property_addition'),
    ('property_address_zip'),
    ('property_block'),
    ('property_city'),
    ('property_county'),
    ('property_lot')
),
target_fields as (
  select f.id as field_id, f.field_key
  from public.fields f
  inner join mapping_field_keys k on lower(f.field_key) = lower(k.field_key)
  where f.status = 'ACTIVE'
)
update public.form_field_mappings ffm
set
  status = 'INACTIVE',
  update_date = now()
from txr_1102_form tf,
     target_fields fld
where ffm.form_id = tf.form_id
  and ffm.field_id = fld.field_id
  and ffm.status = 'ACTIVE';

-- ---------------------------------------------------------------------------
-- First-pass PDF mappings
-- ---------------------------------------------------------------------------

create temp table txr_1102_placement_seed (
  field_key text not null,
  mapping_name text not null,
  occurrence_index integer,
  page_number integer not null,
  x numeric not null,
  y numeric not null,
  width numeric not null,
  height numeric not null,
  field_widget_type text not null
) on commit drop;

insert into txr_1102_placement_seed (
  field_key,
  mapping_name,
  occurrence_index,
  page_number,
  x,
  y,
  width,
  height,
  field_widget_type
)
values
  ('landlord_name_1', 'Page 1 landlord name 1', null::integer, 1, 105, 158, 390, 14, 'text'),
  ('landlord_name_2', 'Page 1 landlord name 2', 1, 1, 105, 158, 390, 14, 'text'),
  ('landlord_address', 'Page 1 landlord address', null::integer, 1, 105, 188, 390, 14, 'text'),
  ('landlord_city_state_zip', 'Page 1 landlord city state zip', null::integer, 1, 150, 218, 345, 14, 'text'),
  ('landlord_phone', 'Page 1 landlord phone', null::integer, 1, 95, 248, 180, 14, 'text'),
  ('landlord_email', 'Page 1 landlord email', null::integer, 1, 95, 278, 250, 14, 'text'),
  ('brokerage_name', 'Page 1 brokerage name', null::integer, 1, 95, 308, 390, 14, 'text'),
  ('brokerage_address', 'Page 1 brokerage address', null::integer, 1, 105, 338, 390, 14, 'text'),
  ('brokerage_city_state_zip', 'Page 1 brokerage city state zip', null::integer, 1, 150, 368, 345, 14, 'text'),
  ('brokerage_office_phone', 'Page 1 brokerage office phone', null::integer, 1, 95, 398, 180, 14, 'text'),
  ('brokerage_email', 'Page 1 brokerage email', null::integer, 1, 95, 428, 250, 14, 'text'),
  ('property_lot', 'Page 1 property lot', null::integer, 1, 120, 510, 65, 14, 'text'),
  ('property_block', 'Page 1 property block', null::integer, 1, 240, 510, 65, 14, 'text'),
  ('property_addition', 'Page 1 property addition', null::integer, 1, 95, 526, 250, 14, 'text'),
  ('property_city', 'Page 1 property city', null::integer, 1, 395, 526, 130, 14, 'text'),
  ('property_county', 'Page 1 property county', null::integer, 1, 85, 542, 120, 14, 'text'),
  ('property_address_zip', 'Page 1 property address zip', null::integer, 1, 250, 542, 300, 14, 'text'),
  ('lease_non_real_estate_items', 'Page 1 non real estate items', null::integer, 1, 95, 628, 470, 28, 'text'),
  ('lease_listing_exclusions', 'Page 1 listing exclusions', null::integer, 1, 95, 690, 470, 28, 'text'),
  ('lease_hoa_is_subject', 'Page 1 HOA is subject', null::integer, 1, 305, 736, 14, 14, 'checkbox'),
  ('lease_hoa_is_not_subject', 'Page 1 HOA is not subject', null::integer, 1, 360, 736, 14, 14, 'checkbox'),
  ('lease_monthly_rent', 'Page 1 monthly rent', null::integer, 1, 250, 765, 90, 14, 'text'),
  ('lease_term_min_months', 'Page 1 term min months', null::integer, 1, 165, 782, 55, 14, 'text'),
  ('lease_term_max_months', 'Page 1 term max months', null::integer, 1, 365, 782, 55, 14, 'text'),
  ('lease_listing_concerning', 'Page 2 listing concerning', null::integer, 2, 200, 32, 320, 14, 'text'),
  ('lease_comp_with_other_broker', 'Page 2 comp with other broker', null::integer, 2, 47, 157, 14, 14, 'checkbox'),
  ('lease_broker_fee_one_month_selected', 'Page 2 broker fee one month selected', null::integer, 2, 72, 218, 14, 14, 'checkbox'),
  ('lease_broker_fee_one_month_percent', 'Page 2 broker fee one month percent', null::integer, 2, 120, 218, 55, 14, 'text'),
  ('lease_broker_fee_all_rents_selected', 'Page 2 broker fee all rents selected', null::integer, 2, 72, 248, 14, 14, 'checkbox'),
  ('lease_broker_fee_all_rents_percent', 'Page 2 broker fee all rents percent', null::integer, 2, 120, 248, 55, 14, 'text'),
  ('lease_broker_fee_other_selected', 'Page 2 broker fee other selected', null::integer, 2, 72, 278, 14, 14, 'checkbox'),
  ('lease_broker_fee_other', 'Page 2 broker fee other', null::integer, 2, 105, 278, 455, 14, 'text'),
  ('lease_other_broker_one_month_selected', 'Page 2 other broker one month selected', null::integer, 2, 72, 395, 14, 14, 'checkbox'),
  ('lease_other_broker_one_month_percent', 'Page 2 other broker one month percent', null::integer, 2, 105, 395, 55, 14, 'text'),
  ('lease_other_broker_all_rents_selected', 'Page 2 other broker all rents selected', null::integer, 2, 72, 425, 14, 14, 'checkbox'),
  ('lease_other_broker_all_rents_percent', 'Page 2 other broker all rents percent', null::integer, 2, 105, 425, 55, 14, 'text'),
  ('lease_other_broker_flat_fee_selected', 'Page 2 other broker flat fee selected', null::integer, 2, 72, 455, 14, 14, 'checkbox'),
  ('lease_other_broker_flat_fee', 'Page 2 other broker flat fee', null::integer, 2, 190, 455, 90, 14, 'text'),
  ('lease_comp_without_other_broker', 'Page 2 comp without other broker', null::integer, 2, 47, 625, 14, 14, 'checkbox'),
  ('lease_no_coop_one_month_selected', 'Page 2 no coop one month selected', null::integer, 2, 72, 686, 14, 14, 'checkbox'),
  ('lease_no_coop_one_month_percent', 'Page 2 no coop one month percent', null::integer, 2, 120, 686, 55, 14, 'text'),
  ('lease_no_coop_all_rents_selected', 'Page 2 no coop all rents selected', null::integer, 2, 72, 716, 14, 14, 'checkbox'),
  ('lease_no_coop_all_rents_percent', 'Page 2 no coop all rents percent', null::integer, 2, 120, 716, 55, 14, 'text'),
  ('lease_no_coop_other_selected', 'Page 2 no coop other selected', null::integer, 2, 72, 746, 14, 14, 'checkbox'),
  ('lease_no_coop_other', 'Page 2 no coop other', null::integer, 2, 105, 746, 455, 14, 'text'),
  ('lease_listing_concerning', 'Page 3 listing concerning', 1, 3, 200, 32, 320, 14, 'text'),
  ('lease_renewal_one_month_selected', 'Page 3 renewal one month selected', null::integer, 3, 47, 128, 14, 14, 'checkbox'),
  ('lease_renewal_one_month_percent', 'Page 3 renewal one month percent', null::integer, 3, 95, 128, 55, 14, 'text'),
  ('lease_renewal_all_rents_selected', 'Page 3 renewal all rents selected', null::integer, 3, 47, 158, 14, 14, 'checkbox'),
  ('lease_renewal_all_rents_percent', 'Page 3 renewal all rents percent', null::integer, 3, 95, 158, 55, 14, 'text'),
  ('lease_renewal_other_selected', 'Page 3 renewal other selected', null::integer, 3, 47, 188, 14, 14, 'checkbox'),
  ('lease_renewal_other', 'Page 3 renewal other', null::integer, 3, 80, 188, 480, 14, 'text'),
  ('lease_sale_comp_percent_selected', 'Page 3 sale comp percent selected', null::integer, 3, 72, 300, 14, 14, 'checkbox'),
  ('lease_sale_comp_percent', 'Page 3 sale comp percent', null::integer, 3, 115, 300, 55, 14, 'text'),
  ('lease_sale_comp_other_selected', 'Page 3 sale comp other selected', null::integer, 3, 72, 330, 14, 14, 'checkbox'),
  ('lease_sale_comp_other', 'Page 3 sale comp other', null::integer, 3, 105, 330, 455, 14, 'text'),
  ('lease_reimbursable_expenses', 'Page 3 reimbursable expenses', null::integer, 3, 80, 515, 480, 42, 'text'),
  ('lease_protection_period_days', 'Page 3 protection period days', null::integer, 3, 410, 585, 55, 14, 'text'),
  ('lease_payment_county', 'Page 3 payment county', null::integer, 3, 360, 735, 130, 14, 'text'),
  ('lease_listing_concerning', 'Page 4 listing concerning', 2, 4, 200, 32, 320, 14, 'text'),
  ('lease_mls_file_listing', 'Page 4 MLS file listing', null::integer, 4, 47, 112, 14, 14, 'checkbox'),
  ('lease_mls_file_immediately', 'Page 4 MLS file immediately', null::integer, 4, 72, 148, 14, 14, 'checkbox'),
  ('lease_mls_delay_filing', 'Page 4 MLS delay filing', null::integer, 4, 72, 205, 14, 14, 'checkbox'),
  ('lease_mls_delayed_days', 'Page 4 MLS delayed days', null::integer, 4, 430, 205, 55, 14, 'text'),
  ('lease_mls_delayed_purpose', 'Page 4 MLS delayed purpose', null::integer, 4, 80, 235, 480, 28, 'text'),
  ('lease_mls_no_filing', 'Page 4 MLS no filing', null::integer, 4, 47, 365, 14, 14, 'checkbox'),
  ('lease_listing_concerning', 'Page 5 listing concerning', 3, 5, 200, 32, 320, 14, 'text'),
  ('lease_scheduling_company', 'Page 5 scheduling company', null::integer, 5, 360, 220, 200, 14, 'text'),
  ('lease_keybox_authorized_yes', 'Page 5 keybox authorized yes', null::integer, 5, 335, 370, 14, 14, 'checkbox'),
  ('lease_keybox_authorized_no', 'Page 5 keybox authorized no', null::integer, 5, 385, 370, 14, 14, 'checkbox'),
  ('lease_intermediary_yes', 'Page 5 intermediary yes', null::integer, 5, 47, 590, 14, 14, 'checkbox'),
  ('lease_listing_concerning', 'Page 6 listing concerning', 4, 6, 200, 32, 320, 14, 'text'),
  ('lease_intermediary_no', 'Page 6 intermediary no', null::integer, 6, 47, 92, 14, 14, 'checkbox'),
  ('lease_internet_no_display', 'Page 6 internet no display', null::integer, 6, 47, 370, 14, 14, 'checkbox'),
  ('lease_internet_no_address_display', 'Page 6 internet no address display', null::integer, 6, 47, 400, 14, 14, 'checkbox'),
  ('lease_listing_concerning', 'Page 7 listing concerning', 5, 7, 200, 32, 320, 14, 'text'),
  ('lease_make_ready_not_authorized', 'Page 7 make ready not authorized', null::integer, 7, 47, 105, 14, 14, 'checkbox'),
  ('lease_make_ready_authorized', 'Page 7 make ready authorized', null::integer, 7, 47, 135, 14, 14, 'checkbox'),
  ('lease_make_ready_cost_cap', 'Page 7 make ready cost cap', null::integer, 7, 420, 150, 90, 14, 'text'),
  ('lease_make_ready_landlord_pays_contractors', 'Page 7 make ready landlord pays contractors', null::integer, 7, 72, 205, 14, 14, 'checkbox'),
  ('lease_make_ready_direct_service_fee', 'Page 7 make ready direct service fee', null::integer, 7, 365, 220, 150, 14, 'text'),
  ('lease_make_ready_broker_reimbursed', 'Page 7 make ready broker reimbursed', null::integer, 7, 72, 250, 14, 14, 'checkbox'),
  ('lease_make_ready_reimbursement_service_fee', 'Page 7 make ready reimbursement service fee', null::integer, 7, 310, 265, 200, 14, 'text'),
  ('lease_known_financial_obligations_exception', 'Page 7 known financial obligations exception', null::integer, 7, 415, 540, 140, 14, 'text'),
  ('lease_known_liens_exception', 'Page 7 known liens exception', null::integer, 7, 95, 585, 460, 14, 'text'),
  ('lease_optional_common_area_fees_exception', 'Page 7 optional common area fees exception', null::integer, 7, 430, 690, 130, 14, 'text'),
  ('lease_health_safety_condition_exception', 'Page 7 health safety condition exception', null::integer, 7, 95, 735, 460, 14, 'text'),
  ('lease_listing_concerning', 'Page 8 listing concerning', 6, 8, 200, 32, 320, 14, 'text'),
  ('lease_special_provisions', 'Page 8 special provisions', null::integer, 8, 80, 665, 480, 60, 'text'),
  ('lease_listing_concerning', 'Page 9 listing concerning', 7, 9, 200, 32, 320, 14, 'text'),
  ('lease_add_iabs', 'Page 9 add IABS', null::integer, 9, 47, 170, 14, 14, 'checkbox'),
  ('lease_add_rental_flood_disclosure', 'Page 9 add rental flood disclosure', null::integer, 9, 47, 195, 14, 14, 'checkbox'),
  ('lease_add_lead_paint', 'Page 9 add lead paint', null::integer, 9, 47, 220, 14, 14, 'checkbox'),
  ('lease_add_hoa_request', 'Page 9 add HOA request', null::integer, 9, 47, 245, 14, 14, 'checkbox'),
  ('lease_add_flood_hazard', 'Page 9 add flood hazard', null::integer, 9, 47, 270, 14, 14, 'checkbox'),
  ('lease_add_condo_addendum', 'Page 9 add condo addendum', null::integer, 9, 47, 295, 14, 14, 'checkbox'),
  ('lease_add_keybox_tenant', 'Page 9 add keybox tenant', null::integer, 9, 47, 320, 14, 14, 'checkbox'),
  ('lease_add_onsite_sewer', 'Page 9 add onsite sewer', null::integer, 9, 47, 345, 14, 14, 'checkbox'),
  ('lease_add_irs_forms', 'Page 9 add IRS forms', null::integer, 9, 47, 370, 14, 14, 'checkbox'),
  ('lease_add_unescorted_access', 'Page 9 add unescorted access', null::integer, 9, 47, 395, 14, 14, 'checkbox'),
  ('lease_add_assistance_animals', 'Page 9 add assistance animals', null::integer, 9, 47, 420, 14, 14, 'checkbox'),
  ('lease_add_other_document', 'Page 9 add other document', null::integer, 9, 47, 445, 14, 14, 'checkbox'),
  ('lease_add_other_document_description', 'Page 9 add other document description', null::integer, 9, 75, 445, 480, 14, 'text'),
  ('lease_rent_due_first_day', 'Page 9 rent due first day', null::integer, 9, 232, 520, 14, 14, 'checkbox'),
  ('lease_rent_due_other_selected', 'Page 9 rent due other selected', null::integer, 9, 380, 520, 14, 14, 'checkbox'),
  ('lease_rent_due_other', 'Page 9 rent due other', null::integer, 9, 400, 520, 150, 14, 'text'),
  ('lease_initial_late_charge_amount_selected', 'Page 9 initial late charge amount selected', null::integer, 9, 155, 590, 14, 14, 'checkbox'),
  ('lease_initial_late_charge_amount', 'Page 9 initial late charge amount', null::integer, 9, 175, 590, 75, 14, 'text'),
  ('lease_initial_late_charge_percent_selected', 'Page 9 initial late charge percent selected', null::integer, 9, 280, 590, 14, 14, 'checkbox'),
  ('lease_initial_late_charge_percent', 'Page 9 initial late charge percent', null::integer, 9, 300, 590, 55, 14, 'text'),
  ('lease_additional_late_charge_daily_amount', 'Page 9 additional late charge daily amount', null::integer, 9, 180, 620, 75, 14, 'text'),
  ('lease_animals_not_permitted', 'Page 9 animals not permitted', null::integer, 9, 112, 665, 14, 14, 'checkbox'),
  ('lease_animals_permitted', 'Page 9 animals permitted', null::integer, 9, 230, 665, 14, 14, 'checkbox'),
  ('lease_animal_restrictions', 'Page 9 animal restrictions', null::integer, 9, 365, 665, 190, 28, 'text'),
  ('lease_animal_deposit', 'Page 9 animal deposit', null::integer, 9, 250, 725, 75, 14, 'text'),
  ('lease_animal_monthly_rent_increase', 'Page 9 animal monthly rent increase', null::integer, 9, 300, 752, 75, 14, 'text'),
  ('lease_listing_concerning', 'Page 10 listing concerning', 8, 10, 200, 32, 320, 14, 'text'),
  ('lease_animal_nonrefundable_fee', 'Page 10 animal nonrefundable fee', null::integer, 10, 270, 72, 75, 14, 'text'),
  ('lease_animal_violation_initial_charge', 'Page 10 animal violation initial charge', null::integer, 10, 175, 112, 75, 14, 'text'),
  ('lease_animal_violation_daily_charge', 'Page 10 animal violation daily charge', null::integer, 10, 310, 112, 75, 14, 'text'),
  ('lease_security_deposit', 'Page 10 security deposit', null::integer, 10, 185, 205, 90, 14, 'text'),
  ('lease_tenant_utilities_except', 'Page 10 tenant utilities except', null::integer, 10, 265, 235, 290, 14, 'text'),
  ('lease_guest_days', 'Page 10 guest days', null::integer, 10, 285, 282, 60, 14, 'text'),
  ('lease_vehicle_count', 'Page 10 vehicle count', null::integer, 10, 285, 312, 60, 14, 'text'),
  ('lease_trip_charge', 'Page 10 trip charge', null::integer, 10, 135, 342, 80, 14, 'text'),
  ('lease_keybox_last_days', 'Page 10 keybox last days', null::integer, 10, 205, 372, 60, 14, 'text'),
  ('lease_early_withdrawal_fee', 'Page 10 early withdrawal fee', null::integer, 10, 420, 372, 80, 14, 'text'),
  ('lease_inventory_condition_form_days', 'Page 10 inventory condition form days', null::integer, 10, 290, 402, 60, 14, 'text'),
  ('lease_yard_landlord', 'Page 10 yard landlord', null::integer, 10, 225, 432, 14, 14, 'checkbox'),
  ('lease_yard_tenant', 'Page 10 yard tenant', null::integer, 10, 300, 432, 14, 14, 'checkbox'),
  ('lease_yard_contractor_tenant_paid', 'Page 10 yard contractor tenant paid', null::integer, 10, 370, 432, 14, 14, 'checkbox'),
  ('lease_yard_contractor_name', 'Page 10 yard contractor name', null::integer, 10, 82, 462, 180, 14, 'text'),
  ('lease_pool_landlord', 'Page 10 pool landlord', null::integer, 10, 225, 492, 14, 14, 'checkbox'),
  ('lease_pool_tenant', 'Page 10 pool tenant', null::integer, 10, 300, 492, 14, 14, 'checkbox'),
  ('lease_pool_contractor_tenant_paid', 'Page 10 pool contractor tenant paid', null::integer, 10, 370, 492, 14, 14, 'checkbox'),
  ('lease_pool_contractor_name', 'Page 10 pool contractor name', null::integer, 10, 82, 522, 180, 14, 'text'),
  ('lease_pool_other', 'Page 10 pool other', null::integer, 10, 47, 552, 14, 14, 'checkbox'),
  ('lease_pool_other_text', 'Page 10 pool other text', null::integer, 10, 75, 552, 480, 14, 'text'),
  ('lease_emergency_repair_phone', 'Page 10 emergency repair phone', null::integer, 10, 285, 600, 150, 14, 'text'),
  ('lease_items_not_repaired', 'Page 10 items not repaired', null::integer, 10, 285, 630, 270, 14, 'text'),
  ('lease_tenant_liability_insurance_amount', 'Page 10 tenant liability insurance amount', null::integer, 10, 455, 660, 90, 14, 'text'),
  ('lease_replacement_tenant_by_tenant_amount_selected', 'Page 10 replacement tenant by tenant amount selected', null::integer, 10, 235, 704, 14, 14, 'checkbox'),
  ('lease_replacement_tenant_by_tenant_amount', 'Page 10 replacement tenant by tenant amount', null::integer, 10, 255, 704, 75, 14, 'text'),
  ('lease_replacement_tenant_by_tenant_percent_selected', 'Page 10 replacement tenant by tenant percent selected', null::integer, 10, 355, 704, 14, 14, 'checkbox'),
  ('lease_replacement_tenant_by_tenant_percent', 'Page 10 replacement tenant by tenant percent', null::integer, 10, 375, 704, 55, 14, 'text'),
  ('lease_replacement_tenant_by_landlord_amount_selected', 'Page 10 replacement tenant by landlord amount selected', null::integer, 10, 235, 734, 14, 14, 'checkbox'),
  ('lease_replacement_tenant_by_landlord_amount', 'Page 10 replacement tenant by landlord amount', null::integer, 10, 255, 734, 75, 14, 'text'),
  ('lease_replacement_tenant_by_landlord_percent_selected', 'Page 10 replacement tenant by landlord percent selected', null::integer, 10, 355, 734, 14, 14, 'checkbox'),
  ('lease_replacement_tenant_by_landlord_percent', 'Page 10 replacement tenant by landlord percent', null::integer, 10, 375, 734, 55, 14, 'text'),
  ('lease_requirements_special_provisions', 'Page 10 requirements special provisions', null::integer, 10, 95, 760, 460, 24, 'text'),
  ('lease_requirements_other', 'Page 10 requirements other', null::integer, 10, 95, 786, 460, 24, 'text'),
  ('lease_listing_concerning', 'Page 11 listing concerning', 9, 11, 200, 32, 320, 14, 'text');

create temp table txr_1102_mappings_touched (
  field_key text not null,
  page_number integer not null,
  occurrence_index integer,
  action text not null
) on commit drop;

with inserted_mappings as (
  insert into public.form_field_mappings (
    form_id,
    field_id,
    mapping_name,
    occurrence_index,
    page_number,
    x,
    y,
    width,
    height,
    page_width,
    page_height,
    font_size,
    field_widget_type,
    notes
  )
  select
    tf.form_id,
    fld.id,
    ps.mapping_name,
    ps.occurrence_index,
    ps.page_number,
    ps.x,
    ps.y,
    ps.width,
    ps.height,
    612,
    792,
    9,
    ps.field_widget_type,
    'TXR-1102 Residential Lease Listing Agreement first-pass placement'
  from txr_1102_placement_seed ps
  inner join txr_1102_form tf on true
  inner join public.fields fld
    on lower(fld.field_key) = lower(ps.field_key)
   and fld.status = 'ACTIVE'
  where not exists (
    select 1
    from public.form_field_mappings existing
    where existing.form_id = tf.form_id
      and existing.field_id = fld.id
      and existing.page_number = ps.page_number
      and coalesce(existing.occurrence_index, -1) = coalesce(ps.occurrence_index, -1)
      and existing.status = 'ACTIVE'
  )
  returning
    (select field_key from public.fields where id = field_id) as field_key,
    page_number,
    occurrence_index
)
insert into txr_1102_mappings_touched (field_key, page_number, occurrence_index, action)
select field_key, page_number, occurrence_index, 'inserted' from inserted_mappings;

-- ---------------------------------------------------------------------------
-- Report
-- ---------------------------------------------------------------------------

do $$
declare
  v_form_id bigint;
  v_fields_inserted integer;
  v_fields_updated integer;
  v_mappings_inserted integer;
  v_unresolved_fields text;
  v_unresolved_mappings text;
begin
  select form_id into v_form_id from txr_1102_form limit 1;

  select count(*) into v_fields_inserted
  from txr_1102_fields_touched where action = 'inserted';

  select count(*) into v_fields_updated
  from txr_1102_fields_touched where action = 'updated';

  select count(*) into v_mappings_inserted
  from txr_1102_mappings_touched where action = 'inserted';

  select string_agg(expected.field_key, ', ' order by expected.field_key)
  into v_unresolved_fields
  from (
    values
      ('brokerage_address'),
      ('brokerage_city_state_zip'),
      ('brokerage_email'),
      ('brokerage_name'),
      ('brokerage_office_phone'),
      ('landlord_address'),
      ('landlord_city_state_zip'),
      ('landlord_email'),
      ('landlord_name_1'),
      ('landlord_name_2'),
      ('landlord_phone'),
      ('lease_add_assistance_animals'),
      ('lease_add_condo_addendum'),
      ('lease_add_flood_hazard'),
      ('lease_add_hoa_request'),
      ('lease_add_iabs'),
      ('lease_add_irs_forms'),
      ('lease_add_keybox_tenant'),
      ('lease_add_lead_paint'),
      ('lease_add_onsite_sewer'),
      ('lease_add_other_document'),
      ('lease_add_other_document_description'),
      ('lease_add_rental_flood_disclosure'),
      ('lease_add_unescorted_access'),
      ('lease_additional_late_charge_daily_amount'),
      ('lease_animal_deposit'),
      ('lease_animal_monthly_rent_increase'),
      ('lease_animal_nonrefundable_fee'),
      ('lease_animal_restrictions'),
      ('lease_animal_violation_daily_charge'),
      ('lease_animal_violation_initial_charge'),
      ('lease_animals_not_permitted'),
      ('lease_animals_permitted'),
      ('lease_broker_fee_all_rents_percent'),
      ('lease_broker_fee_all_rents_selected'),
      ('lease_broker_fee_one_month_percent'),
      ('lease_broker_fee_one_month_selected'),
      ('lease_broker_fee_other'),
      ('lease_broker_fee_other_selected'),
      ('lease_comp_with_other_broker'),
      ('lease_comp_without_other_broker'),
      ('lease_early_withdrawal_fee'),
      ('lease_emergency_repair_phone'),
      ('lease_guest_days'),
      ('lease_health_safety_condition_exception'),
      ('lease_hoa_is_not_subject'),
      ('lease_hoa_is_subject'),
      ('lease_initial_late_charge_amount'),
      ('lease_initial_late_charge_amount_selected'),
      ('lease_initial_late_charge_percent'),
      ('lease_initial_late_charge_percent_selected'),
      ('lease_intermediary_no'),
      ('lease_intermediary_yes'),
      ('lease_internet_no_address_display'),
      ('lease_internet_no_display'),
      ('lease_inventory_condition_form_days'),
      ('lease_items_not_repaired'),
      ('lease_keybox_authorized_no'),
      ('lease_keybox_authorized_yes'),
      ('lease_keybox_last_days'),
      ('lease_known_financial_obligations_exception'),
      ('lease_known_liens_exception'),
      ('lease_listing_concerning'),
      ('lease_listing_exclusions'),
      ('lease_make_ready_authorized'),
      ('lease_make_ready_broker_reimbursed'),
      ('lease_make_ready_cost_cap'),
      ('lease_make_ready_direct_service_fee'),
      ('lease_make_ready_landlord_pays_contractors'),
      ('lease_make_ready_not_authorized'),
      ('lease_make_ready_reimbursement_service_fee'),
      ('lease_mls_delay_filing'),
      ('lease_mls_delayed_days'),
      ('lease_mls_delayed_purpose'),
      ('lease_mls_file_immediately'),
      ('lease_mls_file_listing'),
      ('lease_mls_no_filing'),
      ('lease_monthly_rent'),
      ('lease_no_coop_all_rents_percent'),
      ('lease_no_coop_all_rents_selected'),
      ('lease_no_coop_one_month_percent'),
      ('lease_no_coop_one_month_selected'),
      ('lease_no_coop_other'),
      ('lease_no_coop_other_selected'),
      ('lease_non_real_estate_items'),
      ('lease_optional_common_area_fees_exception'),
      ('lease_other_broker_all_rents_percent'),
      ('lease_other_broker_all_rents_selected'),
      ('lease_other_broker_flat_fee'),
      ('lease_other_broker_flat_fee_selected'),
      ('lease_other_broker_one_month_percent'),
      ('lease_other_broker_one_month_selected'),
      ('lease_payment_county'),
      ('lease_pool_contractor_name'),
      ('lease_pool_contractor_tenant_paid'),
      ('lease_pool_landlord'),
      ('lease_pool_other'),
      ('lease_pool_other_text'),
      ('lease_pool_tenant'),
      ('lease_protection_period_days'),
      ('lease_reimbursable_expenses'),
      ('lease_renewal_all_rents_percent'),
      ('lease_renewal_all_rents_selected'),
      ('lease_renewal_one_month_percent'),
      ('lease_renewal_one_month_selected'),
      ('lease_renewal_other'),
      ('lease_renewal_other_selected'),
      ('lease_rent_due_first_day'),
      ('lease_rent_due_other'),
      ('lease_rent_due_other_selected'),
      ('lease_replacement_tenant_by_landlord_amount'),
      ('lease_replacement_tenant_by_landlord_amount_selected'),
      ('lease_replacement_tenant_by_landlord_percent'),
      ('lease_replacement_tenant_by_landlord_percent_selected'),
      ('lease_replacement_tenant_by_tenant_amount'),
      ('lease_replacement_tenant_by_tenant_amount_selected'),
      ('lease_replacement_tenant_by_tenant_percent'),
      ('lease_replacement_tenant_by_tenant_percent_selected'),
      ('lease_requirements_other'),
      ('lease_requirements_special_provisions'),
      ('lease_sale_comp_other'),
      ('lease_sale_comp_other_selected'),
      ('lease_sale_comp_percent'),
      ('lease_sale_comp_percent_selected'),
      ('lease_scheduling_company'),
      ('lease_security_deposit'),
      ('lease_special_provisions'),
      ('lease_tenant_liability_insurance_amount'),
      ('lease_tenant_utilities_except'),
      ('lease_term_max_months'),
      ('lease_term_min_months'),
      ('lease_trip_charge'),
      ('lease_vehicle_count'),
      ('lease_yard_contractor_name'),
      ('lease_yard_contractor_tenant_paid'),
      ('lease_yard_landlord'),
      ('lease_yard_tenant'),
      ('property_addition'),
      ('property_address_zip'),
      ('property_block'),
      ('property_city'),
      ('property_county'),
      ('property_lot')
  ) as expected(field_key)
  left join txr_1102_fields_touched touched
    on lower(touched.field_key) = lower(expected.field_key)
  where touched.field_key is null;

  select string_agg(
    ps.field_key || ' (page ' || ps.page_number || coalesce(', occ ' || ps.occurrence_index::text, '') || ')',
    ', '
    order by ps.field_key, ps.page_number, ps.occurrence_index
  )
  into v_unresolved_mappings
  from txr_1102_placement_seed ps
  left join txr_1102_mappings_touched touched
    on lower(touched.field_key) = lower(ps.field_key)
   and touched.page_number = ps.page_number
   and coalesce(touched.occurrence_index, -1) = coalesce(ps.occurrence_index, -1)
  where touched.field_key is null
    and v_form_id is not null;

  raise notice 'TXR-1102 Residential Lease Listing Agreement migration report';
  raise notice '  form_id: %', coalesce(v_form_id::text, 'NOT FOUND');
  raise notice '  fields inserted: %', v_fields_inserted;
  raise notice '  fields updated: %', v_fields_updated;
  raise notice '  mappings inserted: %', v_mappings_inserted;

  if v_unresolved_fields is not null then
    raise notice '  unresolved fields: %', v_unresolved_fields;
  end if;

  if v_form_id is null then
    raise notice '  unresolved mappings: form not found; no mappings applied';
  elsif v_unresolved_mappings is not null then
    raise notice '  unresolved mappings: %', v_unresolved_mappings;
  end if;
end $$;
